### ISSUE TITLE
`ambient login`

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#1008]
It's quite hard to figure out what the exact syntax is for "insert general api_token into settings" (I had to guess). But we could very very easily just use [toml_edit](https://crates.io/crates/toml_edit) to do something like `ambient login MY_TOKEN_HERE", and then just show that in the error screen instead.

**Comment by philpax** [comment]
Well that’s embarrassing, it already exists, it’s just not in the error message https://github.com/AmbientRun/Ambient/blob/main/app/src/cli/login.rs
