### ISSUE TITLE
Error when trying to join an instance on the web: ServerPush, invalid integer

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#1020]
Got this when trying to join tangent:

<img width="430" alt="Screenshot 2023-10-03 at 09 31 22" src="https://github.com/AmbientRun/Ambient/assets/1288009/dd63d8fc-bff8-40b5-a0cd-930ed0cc05ac">

**Comment by ten3roberts** [comment]
This was a temporary server fault
