### ISSUE TITLE
Allow the use of namespaces in concept definitions

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#108]
At present, concepts are restricted to single identifiers. This means that there's no way to organise a group of related concepts together, other than putting them in another project.

This should be relatively simple to do (switch to using `IdentifierPathBuf` instead of `Identifier` and update the codegen appropriately).

**Comment by ArberSephirotheca** [comment]
Hi, can I work on it?

Just found this extremely cool project today, and I think this issue would be a good start for me to learn more of the codebase. :)

**Comment by philpax** [comment]
Hi! Yeah, go for it - note that this only really touches our Rust API macro right now (concepts are purely a guest-side feature at present), so I'm not sure if you'll get the full codebase experience. That being said, if you're still interested:

1) Change `Identifier` to `IdentifierPathBuf` here: https://github.com/AmbientRun/Ambient/blob/main/guest/rust/api/api_macros/src/ambient_project/manifest.rs#L13
2) Fix the compile errors.
3) Add a test here for a concept with a namespaced name (like `test::concept`): https://github.com/AmbientRun/Ambient/blob/main/guest/rust/api/api_macros/src/ambient_project/tests.rs
4) Fix the code generation so that the test passes. Namespaces should translate to Rust modules, similarly to how Rust components are. You may want to reuse the [tree logic from here](https://github.com/AmbientRun/Ambient/blob/main/guest/rust/api/api_macros/src/ambient_project/components.rs#L9) (ideally in a way that it can be used for both - maybe change `TreeNodeInner` so that it takes a generic for its leaf values instead of `Component`?)

That should get you across the line. You can run tests by going to the workspace (`cd guest/rust`) and running `cargo test -p ambient_api_macros`. Let me know if you need a hand with anything!
