### ISSUE TITLE
Import arbitrary data via the asset pipeline

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#1101]
We should add something like: "Data" to the (pipeline processor)[https://github.com/AmbientRun/Ambient/blob/main/crates/pipeline_types/src/lib.rs#L46], so that `.json` and other data can be piped through the asset pipeline.

Then we'd also need some way to download data from the asset pipeline in the code, i.e. `get_data(asset::url("my.json")).await`

Meanwhile, for people looking to import arbitrary data, it _is_ possible to just use include_str or include_bytes (see https://doc.rust-lang.org/std/macro.include_str.html)

**Comment by philpax** [comment]
See also #223 (possibly a dupe?)

**Comment by FredrikNoren** [comment]
@philpax Ah yeah, sounds like the same.
