### ISSUE TITLE
ambient serve, fails to add `/content/` to HTTP server routes

### ISSUE THREAD

**Issue by kevzettler** [AmbientRun/Ambient#1127]
I am trying to host the ambient server. I cannot access the `/content` route. I can access the [info](http://64.225.33.240:8999/info), [status](http://64.225.33.240:8999/status), and [ping](http://64.225.33.240:8999/ping) routes.

https://github.com/AmbientRun/Ambient/blob/256172a79d203f0669dce6bf5c9a7fab0cbab5d1/app/src/server/mod.rs#L310-L327

The `/content` route seems to be conditional based on `build_path` https://github.com/AmbientRun/Ambient/blob/256172a79d203f0669dce6bf5c9a7fab0cbab5d1/app/src/server/mod.rs#L329-L334

If I enable debug logs with `RUST_LOG=debug` I can see the logline from:

https://github.com/AmbientRun/Ambient/blob/256172a79d203f0669dce6bf5c9a7fab0cbab5d1/app/src/server/mod.rs#L356

it looks like:
```
01:59:20 DEBUG ambient::server: Starting HTTP interface on `0.0.0.0:8999` build_path=Some("/app/project/build")
```

seems like there is a `build_path` set

I can inspect that build path and it looks like:
```
root@077332830c7c:/app# ls project/build
lsvr7wpee4biw3sleyscm7har4xzjvoa
```

I have a server up and running and  you can hit [/content](http://64.225.33.240:8999/content) and see the 404. What am I missing?

**Comment by pierd** [comment]
What is the command that you are using to start the server?
Are the assets local to the server or is it using a deployed ones (built package accessible via http)?

**Comment by kevzettler** [comment]
@pierd i'm running the docker container with this command:

```
docker run -d -p 8999:8999/tcp -p 9000:9000/udp -v /mnt/volume_sfo2_01/aceclone/:/app/project -e RUST_LOG=debug ambient ./ambient serve --no-proxy --release ./project
```

the package path is :
```
ls /mnt/volume_sfo2_01/aceclone/
```

This is on the local file system which gets mounted into the docker container as a volume to the `/app/project` container directory

Maybe an issue with filesystem permisions? or volume mounting?

**Comment by pierd** [comment]
The `/content` path is 404 - there's nothing returned for that path. There's no automatic directory listing etc. You should be able to access for example: `/content/lsvr7wpee4biw3sleyscm7har4xzjvoa/ambient.toml`.

A longer explanation (or something you can try locally to troubleshoot).

1. I've installed ambient with:
```sh
cargo install ambient
```
2. Installed the latest nightly:
```sh
$ ambient runtime install 0.3.2-nightly-2023-11-01
Installing runtime version: 0.3.2-nightly-2023-11-01
Installed at: "/home/kuba/.local/share/ambientcli/runtimes/0.3.2-nightly-2023-11-01"
$ ambient runtime set-default 0.3.2-nightly-2023-11-01
The default runtime version is now 0.3.2-nightly-2023-11-01
```
3. Created an empty project with it:
```sh
$ ambient new new-ambient-project
```
4. Pulled the most latest docker image:
```sh
$ docker pull ghcr.io/ambientrun/ambient:sha-894ca3b205fcbc9eb75eaefb17d630b6b2ad79b6
```
5. Started it (pretty much your command):
```sh
$ docker run -d -p 8999:8999/tcp -p 9000:9000/udp -v /home/kuba/new-ambient-project:/app/project -e RUST_LOG=info ghcr.io/ambientrun/ambient:sha-894ca3b205fcbc9eb75eaefb17d630b6b2ad79b6 ./ambient serve --no-proxy --release ./project
```
6. Joined it (after a while to give it time to build) to make sure it works:
```sh
$ ambient join
```

Note: I've been checking this on Windows with WSL so I run steps 1-5 in WSL and 1+2+6 in a regular PowerShell.

Now if I do `curl  localhost:8999/content/kizuiausgdbqmbjrdiqjqoq4a6sxrl32/ambient.toml` then I get the regular ambient manifest.
