### ISSUE TITLE
unexpected mouse release event behaviors in web build?

### ISSUE THREAD

**Issue by kevzettler** [AmbientRun/Ambient#1173]
On the client I have these mouse events for mouse button 1 and mouse button 2:
```
    WindowMouseInput::subscribe(move |msg| {
        match (msg.button, msg.pressed) {
            (0, true) => {
                NetworkInput::new(InputEvent::PrimaryFirePress as u8).send_server_reliable()
            }
            (0, false) => {
                NetworkInput::new(InputEvent::PrimaryFireRelease as u8).send_server_reliable()
            }

            (1, true) => {
                NetworkInput::new(InputEvent::SecondaryFirePress as u8).send_server_reliable()
            }
            (1, false) => {
                NetworkInput::new(InputEvent::SecondaryFireRelease as u8).send_server_reliable()
            }
            (_, _) => {} // unkown mouse button
        }
    });
```

On the server I have a `match` function that handles network events like:

```
        match InputEvent::from_u8(msg.input_event).unwrap() {
            InputEvent::SecondaryFirePress => {
                entity::set_component(player_id, secondary_fire_trigger(), true);
            }

            InputEvent::SecondaryFireRelease => {
                entity::set_component(player_id, secondary_fire_trigger(), false);
            }

            InputEvent::PrimaryFirePress => {
                entity::set_component(player_id, primary_fire_trigger(), true);
            }

            InputEvent::PrimaryFireRelease => {
                entity::set_component(player_id, primary_fire_trigger(), false);
            }
    }
```

On a local native build this behaves as expected. `primary_fire_trigger` gets toggled `true/false` on mouse press release.

Unfortunately on the web build I never see the `PrimaryFireRelease` so `primary_fire_trigger` is permanently `true` Weirdly it seems like The mouse 2 release which I'd assume was SecondaryFireRelease may trigger PrimaryFireRelease.

**Comment by ten3roberts** [comment]
Thank you for your report, this is definitely not intended behavior.

From what I know, both the input handling, and server messaging is entirely different on the web compared to native.

I will see what we can do and where the issue lies

**Comment by kevzettler** [comment]
@ten3roberts fyi this issue seemed to resolve its self after I pushed a new build. Not sure what hapened... I will close for now. If I have a reproducible build I will re open.
