### ISSUE TITLE
Revise CLI to remove `--project-path` parameter

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#120]
From a user perspective, having `--project-path` prior to specific commands (i.e. `ambient --project-path some_folder run`) is confusing because it's not always clear when it would be applicable to the command you're running, and most CLI users expect the subcommand to come first.

I suggest we make all relevant commands accept a path and Just Work:tm:, such that `ambient new some/folder`, `ambient run some/folder` etc all work as expected. `ambient new` already does; this logic just needs to be brought over to the other commands.

**Comment by SK83RJOSH** [comment]
I would like to add that the addition of `--debug` had me very confused when it had to be added *before* `run`. 😄

**Comment by philpax** [comment]
Note to myself: once `--debug` is moved, add it to the Debugging section of the mdbook
