### ISSUE TITLE
Expose kinematic bodies to ecs

### ISSUE THREAD

**Issue by SK83RJOSH** [AmbientRun/Ambient#122]
I really want to use triangle meshes with moving objects... which is only possible if the bodies are kinematic 😄 

https://user-images.githubusercontent.com/1371787/220201292-4e39f90b-23af-4fc1-9b09-dd35b46544fa.mp4

**Comment by philpax** [comment]
Can you clarify what you mean by this?

**Comment by SK83RJOSH** [comment]
I want something like `dynamic()` that flags the body with `PxRigidBodyFlag::KINEMATIC` called `kinematic()`. It should create a `rigid_kinematic()` instead of a `rigid_static()`, and copy `translation()`/`rotation()` to the physx world *instead* of `linear_velocity()` and `angular_velocity()`. I think this is somewhat straight forward, just a tad tedious.
