### ISSUE TITLE
Will ambient be mantained again?

### ISSUE THREAD

**Issue by AsessionGuy** [AmbientRun/Ambient#1268]
Hi! I just discovered Ambient while searching for game engines, Rust and ECS and got really impressed by how easy it made multiplayer game development look compared with other engines (bevy, godot, etc).

After finishing the tutorial, I came to GitHub searching for more detailed references and documentation but I found that the project hasn't been maintained for a while now.

I know is kinda mean ask this so please excuse me but it really looked like a great product.

**Comment by philpax** [comment]
Thank you for your interest in Ambient! We're genuinely touched that you found value in our approach to multiplayer game development; we put a lot of thought into making networked gameplay more accessible and developer-friendly, and I'm glad that it was appreciated 🙂 

Unfortunately, the core team is no longer actively maintaining or developing Ambient. While we're proud of what we built and the problems we solved, we've had to move on to other ventures.

That said, Ambient remains open-source, and we'd be supportive of anyone interested in building upon or forking the project. The architecture and solutions we developed could still provide value to the game development community. If anyone is interested in taking up the torch, we'd be happy to provide guidance and context about the codebase.

For now, we recommend exploring other active game engine projects for production use; personally, I've had success with [Bevy](https://github.com/bevyengine/bevy) and [Lightyear](https://github.com/cBournhonesque/lightyear), but it's not quite as turnkey as Ambient. Thank you again for checking out Ambient - it means a lot to know our work resonated with other developers.
