### ISSUE TITLE
Capture mouse / hide cursor

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#136]
We need some way to capture the mouse/hide the cursor. Probably dependent on #6

**Comment by philpax** [comment]
What should the API for this look like, and what should it allow you to do?

**Comment by kevzettler** [comment]
I would suggest copying the high level patterns of the browsers Pointer Lock API:
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

This may have the added benefit for the Ambient browser target because you will need to use that anyways for browser builds.
