### ISSUE TITLE
Ambient server hanging when running minigolf

### ISSUE THREAD

**Issue by SK83RJOSH** [AmbientRun/Ambient#143]
This is reproducible by cloning the minigolf branch and running the game for a short period of time. The server hangs after roughly 20 seconds and everything in the level stops updating besides the water. I'm unable to debug this locally so unfortunately I'll need to pass this one off. 😞

**Comment by SK83RJOSH** [comment]
Some additional triaging information:
 - This issue occurs even if all queries are commented out *besides* the `spawn_query`
 - Happens with both `serve` and `run`; clients that `join` will eventually get disconnected via a timeout
 - Appears like a deadlock, and must be related to the plethora of new components added [here](https://github.com/AmbientRun/Ambient/pull/140/commits/4dd542bfb5c75182efbe052ba67bb4762fc18d50)
 - Probably related to the `player()` entity

**Comment by philpax** [comment]
Just tested minigolf on macOS and can't seem to reproduce this. I let the game idle for a few minutes, then played a round, and the server kept on ticking. 

Can you check if this still happens for you (it should, nothing's really changed)? If so, I'll try Windows x64

**Comment by SK83RJOSH** [comment]
Resolved after merging latest... odd... but I'll take it!
