### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#146]
At present, our release process requires a few manual steps, as seen in [contributing](https://github.com/AmbientRun/Ambient/blob/main/docs/src/contributing.md). We'd appreciate some help with automating this.

We had a POSIX-only [release script](https://github.com/AmbientRun/Ambient/blob/453dc906238ee9cd2cb4e1218acac5a829e7eaf7/scripts/release.sh) using the individual steps of `cargo release`, but we stopped using it because it required SSH authentication on each step and each step took several seconds to run. We have unique needs because of our two workspaces (the runtime and the Rust guest), so we can't use `cargo release` as is.

Our CI takes care of publishing, so all we need is a cross-platform way of running through the steps outlined in `contributing.md` automatically.

**Comment by coddiw0mple** [comment]
I'd like to work on this, I recently worked on automating making releases for my custom Arch ISO

**Comment by philpax** [comment]
Sure, give it a shot! Just fork the repo and see if you can build something that can automatically update everything mentioned in the contributing guide.

The CI already takes care of [publishing releases](https://github.com/AmbientRun/Ambient/blob/main/.github/workflows/release.yml) (we don't publish to Cargo because of our Git dependencies, which we hope to remove) - the main thing I'd like to do is deal with the boring cutting-of-a-release with running the update programs and updating version numbers.

I also didn't mention this in the OP (going to edit it in), but the solution should be cross-platform, too: we develop on all three major desktop platforms, so it's only fair that we can cut a release from all three 😄

I've considered building a dev tool ("campfire", maybe?) in Rust that lives in the workspace and takes care of doing these things for us, so that we could do `cargo run -p campfire -- release 0.1.2` and `cargo run -p campfire -- docs`, but having more than one binary package interferes with `cargo install --git`.  I'm still trying to find an elegant way around that that doesn't involve stuffing our tools into an example!

**Comment by coddiw0mple** [comment]
The rust tool is actually  exactly what I had in mind! 

I was originally planning to make a bash and a batch script for Mac/Linux and Windows systems. But I realized I was gonna update the files with awk /sed on the Unix systems but Windows batch is....terrible for it.

So I thought rust could do this simple task without creating platform specific code and would be easier to modify and maintain. I have also seen systems without awk or sed so there's that.

And as for the issue with cargo install, we can try releasing campfire as a separate global tool? You could add files to be updated in a campfire.toml file.

Or we can just use [cargo-make](https://github.com/sagiegurari/cargo-make)

**Comment by philpax** [comment]
> So I thought rust could do this simple task without creating platform specific code and would be easier to modify and maintain. I have also seen systems without awk or sed so there's that.

Yeah, it's a lot easier to write cross-platform code with Rust. I spent several CI runs the other day trying to fix up the differences between Linux and macOS shell tooling 😅 

> And as for the issue with cargo install, we can try releasing campfire either as a tool in a 'tools' dir or as a separate global tool and maybe even add it in as a submodule? You could add files to be updated in a campfire.toml file.

Yeah - you can see that there's already a `tools` directory, but I had to make the one tool that's there an example to force `cargo install --git` to not consider it. I think there's probably a more graceful solution that lets us have Ambient install by default with `cargo install` _and_ lets us do `cargo run -p campfire -- ...`, but it needs more research.

> Or we can just use [cargo-make](https://github.com/sagiegurari/cargo-make)

Was thinking about that and it's a maybe, but we still need to run some arbitrary Rust code if we want to roll in the docgen as well. (I also don't know how you'd handle the string replacement in a cross-platform way.) If we ditch the idea of a do-it-all tool, cargo-make should work fine.

I'm wondering if we can use the [xtask pattern](https://github.com/matklad/cargo-xtask) - the only thing stopping us would be the `cargo install` issue.

**Comment by coddiw0mple** [comment]
What do you think of this? 

https://aturon.github.io/tech/2018/04/05/workflows/

We can package campfire as a nice tool on crates.io for such tasks and invoke it with `cargo task update_version x.y`

It'll allow us to add more CLI binaries too so we can extend campfire for more tasks :)

**Comment by philpax** [comment]
It would be nice, but I don't think it was ever implemented. Feel free to investigate further, though!

**Comment by coddiw0mple** [comment]
um okay so there's a little fix here. This seems too easy though lol, maybe I am doing something wrong? 

If we have multiple bins in 1 git repo we see that `cargo install --git <repo_link>` fails

![image](https://user-images.githubusercontent.com/38026347/221761490-72797091-f938-4115-a595-42d833c4ef1e.png)

Yet the moment I do `cargo install --git <repo_link> ambient` it works lol. Maybe I didn't understand the issue you were talking about but this seems like a simple fix

**Comment by philpax** [comment]
Yup, you're not wrong - that's actually what we did initially. The main problem is that it's not super intuitive - while that works fine, it's a little weird to have to specify ambient twice. That being said, it was definitely more confusing when it was the name of the tool in question (`generate-docs`) and not campfire - if we can't find a way to mask campfire from the list, I can probably live with that showing up.

**Comment by coddiw0mple** [comment]
Well cargo fundamentally functions in a way to scan all the Cargo.toml files in a repo, which is what allows us to do the `cargo run -p campfire` . You already know this, I am not trying to teach you. But we can't mask a Cargo.toml in cargo install and let it be  un-masked in cargo run right? Plus I'm sure a rust dev won't mind adding 'ambient' to be done installing :)

But if we consider to not want the additional word during install, we can only use cargo-make(from the options considered so far). We can run cargo commands from it, and python/rust script to update values we want through regex match and replace. Just a thought.

**Comment by philpax** [comment]
Yeah, I think you're right. I was really hoping there was an equivalent to `default-members` that would be used for install _or_ that removing the tools from the workspace would allow hiding them from `cargo install`, but this seems like something that can't be fixed without breaking compatibility: 

- https://github.com/rust-lang/cargo/issues/9011
- https://github.com/rust-lang/cargo/issues/9422

I guess we'll just have to live with the extra `ambient` 😅 - looking at [Artichoke](https://github.com/artichoke/artichoke#cargo), which has a similar problem, they also specify the binary name. Given that we hope to publish on crates.io sooner rather than later, this hopefully won't be too problematic in the long-term.

Go for it - build `campfire` as a Rust tool and update `docs/src/user/installing.md`, and we should be good to go.

**Comment by philpax** [comment]
Yeah absolutely, just chuck it in `campfire` as `campfire generate` or something

**Comment by coddiw0mple** [comment]
I have some confusion on [Step 7](https://github.com/AmbientRun/Ambient/blob/main/docs/src/community/contributing.md), can you explain what it means?

**Comment by FredrikNoren** [comment]
Just a heads up that the release process is about to get even more complicated; we need to publish the UI stuff, and in order to do that we need to publish the [guest_bridge](https://github.com/AmbientRun/Ambient/tree/main/crates/guest_bridge). But to do that, we either have to publish a bunch of packages it needs for native to work, or we need to override the Cargo.toml in the release process make it only support the guest api.

**Comment by coddiw0mple** [comment]
oh I'm actually making it (sort of?) configurable using campfire.toml so it may be fine for now

**Comment by philpax** [comment]
> I have some confusion on [Step 7](https://github.com/AmbientRun/Ambient/blob/main/docs/src/community/contributing.md), can you explain what it means?

I wouldn't worry about that, just tell the user to do it themselves (the changelog will have to be human edited for now anyway)
