### ISSUE TITLE
Character controller translation does not work as expected

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#147]
The third person camera example uses a character controller for the player, and updates its `translation`. However, this results in the physics object being forcibly moved to the location where it will ignore any collisions that it encounters.

We should do one of the following:
- expose a function to move the character controller
- make updating `translation` on a CC move the CC instead of translating it
- add another component to give a move target for CCs (e.g. `character_controller_desired_position` or smth)

**Comment by SK83RJOSH** [comment]
Definitely not second option, as I would expect the current behavior when doing that (and I need teleporting sometimes).

The last option feels the most ideal, if we can't reuse linear velocity for this.

**Comment by FredrikNoren** [comment]
I figured we'd always want option 1 anyway, so I started with that. We could add some convenience unit module in the future for doing gravity, sticking to ground, jumping etc.
