### ISSUE TITLE
`angular_velocity()` and `linear_velocity()` don't apply to kinematic bodies

### ISSUE THREAD

**Issue by SK83RJOSH** [AmbientRun/Ambient#148]
We should have a system specific to `rigid_dynamic()` and `kinematic()` that translates velocities to an update of `transform()`. We should also exclude `kinematic()` from `linear_velocity_q` and `angular_velocity_q` since setting these on kinematic bodies is invalid. This will make these behave as users expect for kinematic bodies.

In the meantime, I've already added the necessary changes to `transform_rotation_q` so this should be an easy one.

**Comment by philpax** [comment]
@SK83RJOSH you've fixed this, right?

**Comment by SK83RJOSH** [comment]
Whoops! Forgot to close it out. This is fixed but we may want to revisit `transform().changed()` setting the kinematic target. I can foresee use cases where a teleport is preferred, and so we may want to introduce something similar to what we've done for #147 and use teleporting by default instead.
