### ISSUE TITLE
Glibc > 2.31 needed

### ISSUE THREAD

**Issue by Cqoicebordel** [AmbientRun/Ambient#149]
Not a big deal, and more an FYI than anything else : 
I just wanted to try Ambient on my (K)Ubuntu 20.04 machine and couldn't because the Glibc shipped is v2.31, and Ambient need at least 2.32.

I know it's mostly on me, but just in case it's just a flag change away on your side, I wanted to make sure it would be backward compatible with a still alive LTS.

Don't hesitate to close as a "won't fix" if it's not an easy fix :)

**Comment by philpax** [comment]
Thanks for reporting this! This is likely because the Linux builds are built on `ubuntu-latest` (Ubuntu 22.04) - we'll see if they can be built on 20.04 without too much trouble :)

**Comment by philpax** [comment]
The next release we cut should work on your system if all goes well. Thanks for reporting!
