### ISSUE TITLE
Latest Windows Release is flagged as a Trojan

### ISSUE THREAD

**Issue by coddiw0mple** [AmbientRun/Ambient#152]
Is this Windows Defender just acting up and throwing false positives?

![image](https://user-images.githubusercontent.com/38026347/220879099-d954c341-748b-49a3-8dd3-3d131761ccaa.png)

**Comment by FredrikNoren** [comment]
@coddiw0mple Yeah, I've seen that too, we need to code sign the windows executable to reduce the risk of it flagging it, but even then it can still do false positives. From what I understand windows bases this on usage so it should stop flagging it the more it's used though.

**Comment by coddiw0mple** [comment]
okay thanks, I'll be closing the issue

Also found this [reddit thread](https://www.reddit.com/r/antivirus/comments/p2o2yj/comment/i6al3y7/?utm_source=share&utm_medium=web2x&context=3) on the same thing where other users experienced the same with other stuff so should be safe for anyone else looking for it
