### ISSUE TITLE
HRTF: MIT license violation

### ISSUE THREAD

**Issue by mrDIMAS** [AmbientRun/Ambient#154]
Ambient's [HRTF implementation](https://github.com/AmbientRun/Ambient/blob/main/crates/audio/src/hrtf.rs) looks to be a copy of mine [hrtf crate](https://github.com/mrDIMAS/hrtf/blob/main/src/lib.rs) - even the comments are the same. [Your implementation](https://github.com/AmbientRun/Ambient/blob/main/crates/audio/src/hrtf.rs) does not contain any copyrights required by MIT license, under which the `hrtf` crate is released. Please add the copyright there and add a statement that your implementation is based on `hrtf` crate.

**Comment by ten3roberts** [comment]
Yes you are indeed correct. I originally used your crate but had to make it fit with our streaming source api.

Thanks for your work on the hrtf crate which we are now using with some modifications.

We have now added the appropriate license and links.

**Comment by mrDIMAS** [comment]
Thank you!
