### ISSUE TITLE
GH suggestions

### ISSUE THREAD

**Issue by transitive-bullshit** [AmbientRun/Ambient#158]
Couple of quick wins to increase dev conversions:

- add an image / gif to the top of the readme (like the one from your homepage). many devs bounce super quickly without it
- add a link to https://www.ambient.run on the repo's metadata; currently the repo has a desc but no link

Excited about this project, and you'd be surprised by how much this type of low-hanging fruit can increase dev interest & conversions on this silly / lovely platform.

Cheers 💕

**Comment by philpax** [comment]
Excellent suggestions! I've just added a link to the website. For the animated image/gif/video, we're thinking about re-recording the homepage video with stable frame-pacing - once we have that, we'll certainly add it here, too ❤️

**Comment by philpax** [comment]
Took a bit of time, but the README now features the video for 0.2. Thanks again for the suggestion 🚀

**Comment by transitive-bullshit** [comment]
This is dope – great work, @philpax 🙏
