### ISSUE TITLE
[DISCUSSION] Relicense Ambient under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by AngelOnFira** [AmbientRun/Ambient#160]
I'm not sure where the team stands on it, but I just wanted to bring up the tendency for Rust projects to *eventually* end up dual licensing under MIT/Apache 2.0. To potentially reduce the amount of overhead of doing it in the future, or otherwise have an issue early to reference that discusses the reason it's just MIT, I thought I would open something up.

I don't want to rehash what has been said before, so I'll just link lots of other places that have had good discussions on the topic:

- Bevy (~250 people needed to sign off) https://github.com/bevyengine/bevy/issues/2373
- A post about ["the great relicensing"](https://listed.to/@cmr/7767/the-great-relicensing)
- An example of a bot suggesting that relicense across many Rust projects: https://github.com/sfackler/rust-postgres-macros/issues/19
- [Hackernews comment by Josh Tripplett](https://news.ycombinator.com/item?id=21566968)

As far as I know, the current process would just be getting the internal Ambient team to sign off, plus maybe a few external people that might be working on ongoing contributions.

**Comment by philpax** [comment]
Yeah, I realised this as well earlier today when I was looking through the codebases to attribute. I'm fine with it for the reasons you've mentioned (and the earlier we do it, the better it is). Leaving this one for @FredrikNoren to decide :)

**Comment by FredrikNoren** [comment]
Hm yeah I don't see any reason not to do this; let's do it Monday unless we find some reason why we shouldn't.

**Comment by ten3roberts** [comment]
We since have one external PR, so we will have to make sure the author agrees to the relicense

**Comment by philpax** [comment]
@daniellavoie Are you okay with your fix being relicensed?

**Comment by daniellavoie** [comment]
I agree! Would be rude not to agree given the nature of the contribution 😅
