### ISSUE TITLE
Add cylindrical primitive and collider

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#163]
We support spheres, cubes/boxes and planes/quads (we should unify the terminology here), but cylinders are missing from both physics and primitive shapes. (A character collider could technically be used for cylinders, but institutes other constraints.)

**Comment by SK83RJOSH** [comment]
They don't exist in PhysX, so I would say there's pretty good reason not to do this for now. You're stuck with triangular meshes, which have a number of limitations, and a performance hit. I would wait for PhysX 5 here since it's far easier to add cylinders as a first class citizen there.

**Comment by philpax** [comment]
You're right, I'll close this for now and think of a better solution later
