### ISSUE TITLE
Remove `State` from the API

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#166]
`State` was a wrapper I added to make sharing state between blocks of code easier. However, it has since been superseded by custom components - we should remove it before it's actively used by others.

**Comment by SK83RJOSH** [comment]
It's used by golf to effectively store a `.resource()` – if those aren't already exposed, they should be. 🙂

**Comment by philpax** [comment]
You can do `entity::add_component(entity::resources(), comp(), value)`. Still undecided as to if we should add helpers for `[add|set|get|remove_]resource` - seems like a fair bit of API bloat for something that may not be used all that often, especially when you can create your own resources-like entity.

**Comment by SK83RJOSH** [comment]
> You can do `entity::add_component(entity::resources(), comp(), value)`. Still undecided as to if we should add helpers for `[add|set|get|remove_]resource` - seems like a fair bit of API bloat for something that may not be used all that often, especially when you can create your own resources-like entity.

I think that's fine for now, so I'll go ahead and fix that up tomorrow. Cheers 👍

**Comment by philpax** [comment]
There's a need for more complex state than is currently possible with custom components (e.g. nested `Vec`s).

I'm going to close this for now, but add a comment to `State` to suggest you use custom components unless you need something that cannot be represented by them.
