### ISSUE TITLE
Debug UI is rendering too small to read.

### ISSUE THREAD

**Issue by kevzettler** [AmbientRun/Ambient#192]
using the debug mode of `ambient run --debug` The debug UI renders but it is too small to read

<img width="483" alt="image" src="https://user-images.githubusercontent.com/126209/222211195-3cfc421c-f4f7-402b-a23a-6a80d435a222.png">

Per discussion on discord at:
https://discord.com/channels/894505972289134632/1078283561540530216/1080411889449832478

hierachy.yml
https://gist.github.com/kevzettler/e0b7f261653dcc1cd6c4b1961a422114

renderer.txt
```
  shadow
    shader "standard_shader_pbr_material_shader_true-true"
      material "material000": 18 entities
  forward
    shader "standard_shader_pbr_material_shader_true-true"
      material "material000": 18 entities
    shader "standard_shader_flat_material_shader_true-false"
      material "62m7s8mU8EuEvizkBXk9w1": 1 entities
  transparent
    0 entities
  outlines
```

server_hiearchy.yml
https://gist.github.com/kevzettler/40419d3340a0a99aecbbc3c073305ff1

**Comment by kevzettler** [comment]
Have updated the hiearchy.yml dump with suggested changes from:

https://discord.com/channels/894505972289134632/1078283561540530216/1080542583224279200

**Comment by philpax** [comment]
That UI dump is super useful, thanks! Not sure when we'll have a chance to investigate, but is there any further information you can provide about your system? e.g. OS, display and scaling settings, GPU. I'm guessing a recent-ish macOS with an external display that runs at a different DPI to your main display?

**Comment by kevzettler** [comment]
**This issue occurs without using an external display. Happens on built in laptop display.**
```
% uname -a
Darwin kevs-mbp-3.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
```

<img width="578" alt="image" src="https://user-images.githubusercontent.com/126209/222228282-3bbd1c2c-970f-4a17-b222-d89ff2c69d9b.png">


<img width="587" alt="image" src="https://user-images.githubusercontent.com/126209/222228436-a8bda052-5e6d-4208-ad7b-484e04eb87c3.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/126209/222229090-dd2a322a-1231-4034-b9e2-81e3b4a056e5.png">


<img width="670" alt="image" src="https://user-images.githubusercontent.com/126209/222230072-ffde3c0d-eb21-4362-876d-5f12f3edf183.png">

**Comment by philpax** [comment]
That's... really weird (we develop on similar hardware). Thanks for the info, we'll look into it!

**Comment by owenpalmer** [comment]
I have the same resolution (2560x1600) on my LG gram, and the same issue occurs.

Intel(R) Iris(R) Plus Graphics
Windows 10

**Comment by philpax** [comment]
Okay yep, reproduced it - it's definitely an issue with scaling. Thanks for reporting, we'll look into it!

**Comment by FredrikNoren** [comment]
I ran git bisect and the bug was introduced in either https://github.com/AmbientRun/Ambient/commit/27f3f079b441483a928d8650a5f9d9cad9184824 or https://github.com/AmbientRun/Ambient/commit/b210d7b6d8f49cd95a96ad33a8c1c6f6c9ee947e @ten3roberts

**Comment by ten3roberts** [comment]
I managed to reproduce the issue and fix it on my side.

Let me know if it is now also fixed on your end
