### ISSUE TITLE
Add component `Description` automatically from rust comment

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#197]
Right now we have to do this to both get the description in the API docs and on the component:

```rust
components!("app", {
    // My fancy test component
    @[Description["My fancy test component"]]
    testy: String,
});
```

It would be nice if doing just `// comment` would automatically add a `Description` to the component.

**Comment by ten3roberts** [comment]
The `// comment` is not possible as `//` comments are stripped before macro invocations.

Capturing doc-comments have to be done in the form of meta-attributes, e.g `#[doc = "comment"]`

**Comment by FredrikNoren** [comment]
@ten3roberts Oh sorry, I mean `///`. Is that also not possible?

**Comment by ten3roberts** [comment]
I may have been a bit unclear.

Capturing doc-comments `/// comment` is definitely possible, although a little tricky.

What I meant i that they need to be matched in the `#[doc = "comment"]` style as they desugar into that before the macros are evaluated. The `/// comment` syntax is only sugar.

In fact, we already capture doc attributes, but only forward them to the declared component function
