### ISSUE TITLE
`BTreeMap::<K, V>::new` is not yet stable as a const fn 

### ISSUE THREAD

**Issue by luojiong** [AmbientRun/Ambient#199]
Env 
   rust  version  1.65.0
  Os version windows10

 Im run `cargo install --git https://github.com/AmbientRun/Ambient.git --tag v0.1.1`  error

**Comment by luojiong** [comment]
<img width="1218" alt="1677803513737" src="https://user-images.githubusercontent.com/28083937/222601009-23326beb-f2f8-482e-983d-ea08f74bd689.png">

**Comment by philpax** [comment]
Our minimum supported Rust version is 1.67.0; we could use polyfills to lower this, but we haven't had much reason to do so. Is there anything that would block you from updating your Rust version?

**Comment by luojiong** [comment]
thanks    Im try new Rust Version

**Comment by luojiong** [comment]
Im update Rust Version by `1.67.1` resolve the problem thanks  @philpax
