### ISSUE TITLE
Add Entity attribute assertions

### ISSUE THREAD

**Issue by ten3roberts** [AmbientRun/Ambient#200]
It would be useful to assert that all components in an `Entity` have a specific attribute, for example `Networked` to ensure that all components you are adding to the entity will also be mirrored on the client.

Currently, non-networked components are silently ignored, and can lead to bugs if you forget to annotate your components.

For example;
```rust
let entity = Entity::new().set(my_non_networked_component(), 5.);
entity.assert_all(Networked);
```

**Comment by MavethGH** [comment]
I can do this one

**Comment by MavethGH** [comment]
Done. Also totally unrelated: @ten3roberts, your GitHub bio is eerily similar to mine.
