### ISSUE TITLE
`ambient new` doesn't use the correct dependency for nested folders in `guest/rust/examples` 

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#214]
Pretty simple issue. 

https://github.com/AmbientRun/Ambient/blob/727c2009f922bd5bbf275056a6456e7864cdabea/app/src/cli/new_project.rs#L32-L53

This logic special-cases the reference to `ambient_api` so that if a project is created in `guest/rust/examples`, the local API is used instead of `crates.io`. Unfortunately, this doesn't work for `guest/rust/examples/basic`.

I would suggest adjusting the logic to find where `guest/rust/examples` is present in the segments (if it is), and then using that to construct the number of `../` in the `GuestRustRelative` case.

**Comment by owenpalmer** [comment]
I've implemented a solution, and I'll make a pull request when I get home.
