### ISSUE TITLE
Implement Debug on Entity (guest API)

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#220]
Would be great with if `Entity` implemented `std::fmt::Debug`:  https://github.com/AmbientRun/Ambient/blob/main/guest/rust/api/src/internal/component/mod.rs#L56 

It should print each component and its value.

**Comment by philpax** [comment]
Note that the API doesn't currently have a way to get the name of a component, so you'll need to add something to the WIT to do this. I'd suggest waiting until I've landed #190.
