### ISSUE TITLE
Enum's for `ambient.toml` components

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#221]
The `ambient.toml` components currently only support primitive types, but a lot of APIs require enum type data. Perhaps something like this:

```rust
[project]
id = "my_project"
name = "My project"
version = "0.0.1"

[types]
PlayerState = { enum = ["Alive", "Dead", "Dying"] }

[components]
player_state = { type = "PlayerState", name = "Player state" }
```

**Comment by philpax** [comment]
Yup, this is something we've been discussing a fair bit internally. We'd like to be able to support structs and to support using types from other projects, so #107 and related work will come into play as well.

**Comment by FredrikNoren** [comment]
@philpax Yup, more advanced types would be awesome also, but I wonder if there's a smaller step we could take of just starting with Enums, as they could be sent over using the u32 primitive and then converted on either side? But yeah I imagine generating on the native side would be a pre-requisite even then.

Anyway figured we'd start tracking the issue at least, there's some stuff in the UI code that would benefit from plain Enums.

**Comment by philpax** [comment]
Yep, definitely. Just making a note for anyone else reading, too.
