### ISSUE TITLE
Rename `EventResult` and `EventOk`

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#241]
These are used in non-events, and aren't particularly descriptive. I'm thinking of renaming them to `EmptyResult` and `EmptyOk`, or similar.

**Comment by FredrikNoren** [comment]
@philpax How about standard rust syntax like `Result<()>`?

**Comment by philpax** [comment]
Yeah, that's also an option; I wanted something that was self-descriptive for people new to Rust, but it may not be necessary. `EventOk` also helps with type deduction (it's just `anyhow::Ok(())`).
