### ISSUE TITLE
Tic tac toe example crashes wgpu

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#249]
Getting the following error when running the tictactoe example:

```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a ComputePass
      note: encoder = `GameState.render`
    In a dispatch command, indirect:false
      note: compute pipeline = `collect`
    the pipeline layout, associated with the current compute pipeline, contains a bind group layout at index 0 which is incompatible with the bind group layout associated with the bind group at 0
```

**Comment by ten3roberts** [comment]
Strange, as collect works on the other examples and the minigolf game, where the collect pipeline runs.

Does it only occur on the tictactoe game, and is is machine dependent or not?

**Comment by FredrikNoren** [comment]
@ten3roberts All other examples that are run by the golden image test scripts works, but haven't tried any of the others (like golf). Have only tested on osx.

**Comment by ten3roberts** [comment]
Alright.

It was expected that *something* would not work considering how large the changes in the shader were, especially as all the bind groups moved around.

Now the question is what makes `TicTacToe` different from the other examples such as `minigolf` which works.

Most likely it is a bind group ordering issue, of that the full `global_bind_group` is supplied where the limited meta bind group is expected.

**Comment by FredrikNoren** [comment]
@ten3roberts Guessing it got something to do with outlines rendering
