### ISSUE TITLE
`ambient new` fails when ambient is installed via `cargo install --git`

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#255]
When Ambient is installed through `cargo install --git`, the following code

https://github.com/AmbientRun/Ambient/blob/062370f82e18aab287e3f3983475f1bc59f4c1d9/app/src/cli/new_project.rs#L64-L70

does not work, as the information about the Git version is erased. This was encountered on the Discord: https://discord.com/channels/894505972289134632/1082217873189126154/1089255480049807433

**Comment by FredrikNoren** [comment]
Reprod on windows

**Comment by FredrikNoren** [comment]
Fixed and seems to work on Windows
