### ISSUE TITLE
Sliders do not respond correctly under DPI-scaled environments

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#257]
The `examples/ui/slider` example works fine at 100% DPI, but behaves incorrectly if the scaling is more than 100%. It's likely that the scaling is either not being applied or being double-applied somewhere.

**Comment by philpax** [comment]
This is still an issue - this is using a MacBook Pro running at the "More Space" setting (but any setting should do, as macOS doesn't let you run unscaled for the Retina Displays):

![slider](https://user-images.githubusercontent.com/707827/229761387-65473c89-e869-4703-a9fc-6b2d28566ecc.gif)

**Comment by FredrikNoren** [comment]
@philpax Thanks, turns out it was an issue for more stuff too (debugger) so fixed all of it

**Comment by philpax** [comment]
Can confirm that fixes it, thanks!
