### ISSUE TITLE
Can't input just after `ambient run`

### ISSUE THREAD

**Issue by hatoo** [AmbientRun/Ambient#277]
Every time I run `ambient run`, a window is focused but I can't input anything and I need to re-focus the window to input. It's a little annoying to me.

This is because the app initializes the `has_focus` state by `false`.

I've come up with an easy fix that is modifying 
https://github.com/AmbientRun/Ambient/blob/3f525028152b4595f14604357cd7cfb3c869f48b/app/src/client/player.rs#L29
to
```rust
    let (has_focus, set_has_focus) = hooks.use_state(true);
```
but it may not work well for other platforms.

I'm running on Windows 11.

**Comment by philpax** [comment]
Fixed - thanks for reporting! We generally assume the window is focused when it's started, so I've used your proposed fix.
