### ISSUE TITLE
playing animations with local_to_parent() breaks transform inheritence? 

### ISSUE THREAD

**Issue by kevzettler** [AmbientRun/Ambient#280]
I have a scene setup with one entity that acts as the player root and another mesh entity that is a child and local_to_parent of the root. The mesh seems to inherit the root parent transform successfully. However when I start playing animations on the mesh it starts to glitch out between the local_to_parent transform and then also the animation local transform:

I tried to capture in this gif
![animation_glitch](https://user-images.githubusercontent.com/126209/229331120-965a3658-340f-454b-a3be-71666223e9c0.gif)

I have an example reproduction project available at: https://github.com/kevzettler/ambient-test-project

**Comment by FredrikNoren** [comment]
Hi!

So the problem is that the mecha also needs the `parent` component; i.e. line 49 add `.with(parent(), id)`.
You will also have a problem that the animations keep restarting each frame with the code above; I'd suggest keeping state if the mecha was walking, and only change the anim when it transitions, i.e.:

```rust
if !was_walking && is_walking { // play walk
    entity::set_animation_controller(
        player_mesh_id,
        AnimationController {
            actions: &[AnimationAction {
                clip_url: &asset_url("assets/mecha.glb/animations/walk_2.anim").unwrap(),
                looping: true,
                weight: 1.,
            }],
            apply_base_pose: false,
        },
    );
}else if was_walking && !is_walking { // idle
    entity::set_animation_controller(
        player_mesh_id,
        AnimationController {
            actions: &[AnimationAction {
                clip_url: &asset_url("assets/mecha.glb/animations/idle_1.anim").unwrap(),
                looping: true,
                weight: 1.,
            }],
            apply_base_pose: false,
        },
    );
}
```

Hope that helps!
