### ISSUE TITLE
transparency_groups not working?

### ISSUE THREAD

**Issue by kevzettler** [AmbientRun/Ambient#293]
I have 2 meshes with `transparency_group` components applied at:
https://github.com/kevzettler/ambient-test-project/blob/master/src/lib.rs#L33-L46

These meshes are used for debugging. one is the cameras lookat position and one is the source of the camera. The nearest one, the view_center_mesh should be transparent allowing the visibility of the far away target mesh 

![image](https://user-images.githubusercontent.com/126209/230784617-c4147101-b3e8-4bb0-8a74-0c59e72d7082.png)

This doesn’t  seem to work whats wrong? this is on `ambient 0.1.1`

**Comment by FredrikNoren** [comment]
@kevzettler I just added a transparency example + fixed a bug, so transparency_groups should work for individual entities now (https://github.com/AmbientRun/Ambient/commit/28da782c3aeeef70b6a8ab96854f0bb61a67cf0c)

It's a bit trickier for entire models though; you would need to both apply `transparency_group` and `color` to each entity in the model tree. It _might_ work for you already if the model happens to only have one entity. Anyway, I've created an issue for it [here](https://github.com/AmbientRun/Ambient/issues/299), so closing this one now as transparency_groups now should work.
