### ISSUE TITLE
Should we save assets locally to avoid  request loading from server every time?

### ISSUE THREAD

**Issue by chaosprint** [AmbientRun/Ambient#294]
When calling `asset::url`
check if `~/Document/Ambient/GAME_NAME/content/assets/ASSET.FILE` exist
if not, request it from the server

In future web version, we can use `Web Storage API`

related to this PR: https://github.com/AmbientRun/Ambient/pull/290

**Comment by philpax** [comment]
Yes, we had this originally; we ended up disabling it because it would use the old versions of files instead of new files. The solution to this will probably involve #12.

**Comment by FredrikNoren** [comment]
Like @philpax said, this already exists, but we need to implement cache invalidation: #81 Closing this issue in favour of that one.
