### ISSUE TITLE
Basic procedural mesh / texture generation

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#30]
This does not support updating meshes or more complicated functionality. This is purely to enable basic procedural mesh generation.

A basic API for creating assets at runtime, just to enable simple creation, and only on the client.

```rust
mod experimental {
  mod texture {
   fn create_2d(data: &[u8], format: texture::Format) -> Result<String, TextureCreateError> {}
  }

  mod material {
    fn create(diffuse_url: &str, /* material parameters */) -> Result<String, MaterialCreateError> {}
  }

  mod mesh {
    fn create(vertices: &[Vertex], indices: &[u32]) -> Result<String, MeshCreateError> {}
  }
}

use experimental::*;

let heightmap = make_heightmap();

let (vertices, indices) = convert_heightmap_to_mesh(&heightmap);
let mesh_url = mesh::create(&vertices, &indices)?;

let diffuse_url = convert_heightmap_to_diffuse(&heightmap);
let diffuse_tex_url = texture::create_2d(&diffuse_url, texture::Format::Rgba8Unorm)?;
let material_url = material::create(&diffuse_tex_url, /* ... */)?;

let id = make_transformable()
  .with(components::mesh_from_url(), mesh_url)
  .with(components::material_from_url(), material_url)
  .spawn();
```

**Comment by FredrikNoren** [comment]
@VinhTruongAmbient We'll need a plan for how we handle lifetimes of these objects to. Also how does it work across modules; i.e. if I create a model url and then send the url with a message somewhere else; how can we make sure lifetimes work appropriately?

**Comment by VinhTruongAmbient** [comment]
> @VinhTruongAmbient We'll need a plan for how we handle lifetimes of these objects to. Also how does it work across modules; i.e. if I create a model url and then send the url with a message somewhere else; how can we make sure lifetimes work appropriately?

The original proposal laid out by @philpax was to keep this feature client-only, at least for now. Not sure about the lifetimes though. The internal rendering code uses Arc very liberally, so it's not yet clear to me when the resources are dropped.
