### ISSUE TITLE
DEMO

### ISSUE THREAD

**Issue by luojiong** [AmbientRun/Ambient#318]
The prospects of this engine are promising.  Can you create a demo to run on 'github. io'  ？

**Comment by chaosprint** [comment]
Thanks for your post. Yes, we are working on this: https://github.com/AmbientRun/Ambient/issues/151

We have mentioned that in the roadmap (https://github.com/AmbientRun/Ambient#roadmap) as well.

**Comment by luojiong** [comment]
Thank you for your work. I look forward to it very much
