### ISSUE TITLE
Physics visualizer doesn't work with multiple players

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#322]
The `visualizing` component doesn't work properly when multiple users are connected

**Comment by philpax** [comment]
Is this an issue that arises from the visualization logic specifically? I was seeing some odd behaviour where I had text attached to player entities, and P2 (joined after) could see both P1 and P2's texts but P1 couldn't see P2's text.

Didn't dig too deeply into it, but could be the same root cause if it's not an issue with the viz logic itself?

**Comment by FredrikNoren** [comment]
I'm not sure but I feel like I saw something similar to what you're describing with @pierd the other day; it felt like two users controlled one camera

**Comment by philpax** [comment]
@ten3roberts do you know if this still happens with your changes?

**Comment by droqen** [comment]
Not 100% sure if this is related or is the problem, but I noticed that `visualize_colliders` doesn't update unless the visualized object is actually moving around, so if there is e.g. a clientside camera moving around while looking at a bunch of static cubes, it won't update the visualize and all the static cubes will be frozen in place.

Let me know if this is related or not so I can make this a new issue if needed.

**Comment by ten3roberts** [comment]
I am having some issues understanding what is the original issue?

How doesn't it work?

<img width="2035" alt="image" src="https://github.com/AmbientRun/Ambient/assets/25723553/345976d3-633a-4dad-b63e-730518ba6fc5">

**Comment by philpax** [comment]
> I am having some issues understanding what is the original issue?
> 
> How doesn't it work?
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/25723553/257509495-345976d3-633a-4dad-b63e-730518ba6fc5.png">

It's probably fixed now 😅

**Comment by FredrikNoren** [comment]
Closing then, as it seems fixed :)
