### ISSUE TITLE
Support FBX EmissiveColor

### ISSUE THREAD

**Issue by owenpalmer** [AmbientRun/Ambient#345]
When an FBX has an `EmissiveColor` property, the model importer doesn't handle it which results in this error.
`thread 'tokio-runtime-worker' panicked at 'Unrecognized texture: Some("EmissiveColor")', crates/model_import/src/fbx/mod.rs:270:30`
https://github.com/AmbientRun/Ambient/blob/000cd0fcf89fc34cc570758b5f711b14780d3f33/crates/model_import/src/fbx/mod.rs#L261-L271

This came up in [the discord channel](https://discord.com/channels/894505972289134632/894505972914065429/1099057005060169800).

**Comment by darshan3v** [comment]
[ch15PBR.fbx.zip](https://github.com/AmbientRun/Ambient/files/11300906/ch15PBR.fbx.zip)

This is the character which has Emissive Color in one of its materials (it has 2 materials)
