### ISSUE TITLE
`includes` in ambient.toml

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#346]
The [main ambient.toml](https://github.com/AmbientRun/Ambient/blob/main/ambient.toml) is getting quite long; perhaps we could add an `includes: ["other.toml"]` to the top of it to break it up?

**Comment by philpax** [comment]
Seems reasonable to me. There are some nuances here around hierarchy and merging (e.g. if A includes B which includes C and they all partially define some `[components]`, C should form the base, B gets merged in, followed by A) - but that's not too bad.
