### ISSUE TITLE
`ambient-asset:/` paths don't work with `audio::load`

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#350]
If you pass a URL from `asset::url` on the server to `audio::load`, you get an error:

```
[2023-04-25T07:29:00Z ERROR ambient_wasm::client::implementation::specific] ContentDownload(builder error for url (ambient-assets:/assets/BD2500.wav): URL scheme is not allowed
    
    Caused by:
        URL scheme is not allowed
```

**Comment by chaosprint** [comment]
I am looking into this issue.
Is it related to https://github.com/AmbientRun/Ambient/actions/runs/4794534058/jobs/8528021152 ?

**Comment by philpax** [comment]
Don't think so, looks like it failed to initialise an audio device or something?

**Comment by chaosprint** [comment]
@philpax @pierd 

`asset::url` on server will return an URL with an `ambient-asset:/` prefix
while `asset::url` on client will not give the URL with the prefix `ambient-asset:/`.

`AbsAssetUrl::from_asset_key` won't recognise `ambient-asset:/` prefix and will return URL with `ambient-asset:/ambient-asset:/` prefix.

So where should we stop a prefix?

**Comment by pierd** [comment]
> `asset::url` on server will return an URL with an `ambient-asset:/` prefix
> while `asset::url` on client will not give the URL with the prefix `ambient-asset:/`.

Yeah, on server gives special URLs while the client resolves them to directly downloadable ones.

Hmm, `AbsAssetUrl::from_asset_key` shouldn't be used with `ambient-asset:/` urls.

**Comment by chaosprint** [comment]
> > `asset::url` on server will return an URL with an `ambient-asset:/` prefix
> > while `asset::url` on client will not give the URL with the prefix `ambient-asset:/`.
> 
> Yeah, on server gives special URLs while the client resolves them to directly downloadable ones.
> 
> Hmm, `AbsAssetUrl::from_asset_key` shouldn't be used with `ambient-asset:/` urls.

So I will just `.replace` the `ambient-asset:/` during `audio::load` then @philpax .

**Comment by pierd** [comment]
You should be able to `AbsAssetUrl::parse` it and then get a downloadable URL (`AbsAssetUrl::to_download_url`).

**Comment by philpax** [comment]
Yep, you can resolve the path through `to_download_url`. It occurs to me that we should use the same solution wherever an asset URL is provided in the API - I'd suggest adding a helper function that "does the right thing" to resolve an URL.
