### ISSUE TITLE
Mesh disappears at camera near distance 

### ISSUE THREAD

**Issue by kevzettler** [AmbientRun/Ambient#372]
My player mesh is disapearing when the camera hits certain near threshold or something. You can see in the gif below. How can I troubleshoot and improve?

This is on commit 7daa5ef9fdf6fc2ffddd704826f9974604b090ee

available for review on: https://github.com/kevzettler/ambient-test-project

![nearplane](https://user-images.githubusercontent.com/126209/236722166-d4ff5bf6-8013-41a7-86f0-25d5f2e93f4a.gif)

**Comment by philpax** [comment]
Is this something you can look into, @VinhTruongAmbient ?

**Comment by VinhTruongAmbient** [comment]
I suspect the near clipping plane is set too far away. Can you try something like `.with(near(), 0.001)` when you create your camera?

**Comment by kevzettler** [comment]
Ok yes the `near` adjustment has resolved the issue.
