### ISSUE TITLE
Broken IDE intellisense for input, frame modules and others.

### ISSUE THREAD

**Issue by kevzettler** [AmbientRun/Ambient#375]
I'm working on some input handling features and have some Ambient code like:

```
   let mut cursor_lock = input::CursorLockGuard::new(true);
    ambient_api::messages::Frame::subscribe(move |_| {
        let (delta, input) = input::get_delta();
```

I wanted to learn more about `input::get_delta` and `messages::Frame`  However my IDE cannot look up any definitions,implementations, or declarations for these modules. I have tried in both emacs, and vscode There are gifs below.

in emacs:

![emacs](https://user-images.githubusercontent.com/126209/236883211-aa63f4df-31e2-4454-853d-a8b9ab6ea54c.gif)

And in Vscode

![vscode](https://user-images.githubusercontent.com/126209/236883251-48259ac3-04c7-45fd-aaaa-5ff33369ecd1.gif)

 Is this a greater configuration issue on my machine? If this is expected behavior this is very unfortunate developer experience. Seems to break expected conventions and very cumbersome to have to go look at Ambient source code directly.

**Comment by philpax** [comment]
This is definitely not intentional; it's an issue with rust-analyzer not being able to handle the attribute proc macros. If you comment out the `#[main]` attribute, your intellisense will work properly.

I'll see if I can chat to the rust-analyzer folk about why this is happening, and what we can do to prevent it.

**Comment by kevzettler** [comment]
yes I do see the `#[main]` macro highlighted with:

``` server.rs    51   1 error    unresolved-proc-macro proc macro `main` not expanded: no proc macro dylib present (lsp)```

@philpax this is currently happening in my public project at:
https://github.com/kevzettler/ambient-test-project

**Comment by philpax** [comment]
Cheers, I'll have a look soon!

I notice that you have a direct dependency on `ambient_api`:
```toml
ambient_api = { path = "/Users/kevzettler/code/Ambient/guest/rust/api" }
```

Do you still see the same issue if you switch to using `ambient_api = "0.2.1"`?

**Comment by kevzettler** [comment]
@philpax I just switched to `ambient_api = "0.2.1"` and did `cargo update`

```
/Users/kevzettler/code/ambient-test-project
kevzettler@kevs-mbp-3 ambient-test-project % cargo update
    Updating crates.io index
      Adding ambient_api v0.2.1
      Adding ambient_api_core v0.2.1
      Adding ambient_api_macros v0.2.1
      Adding ambient_cb v0.2.1
      Adding ambient_color v0.2.1
      Adding ambient_editor_derive v0.2.1
      Adding ambient_element v0.2.1
      Adding ambient_element_component v0.2.1
      Adding ambient_friendly_id v0.2.1
      Adding ambient_guest_bridge v0.2.1
      Adding ambient_math v0.2.1
      Adding ambient_project v0.2.1
      Adding ambient_project_macro_common v0.2.1
      Adding ambient_project_rt v0.2.1
      Adding ambient_schema v0.2.1
      Adding ambient_shared_types v0.2.1
      Adding ambient_time v0.2.1
      Adding ambient_ui v0.2.1
    Updating libc v0.2.143 -> v0.2.144
    Updating quote v1.0.26 -> v1.0.27
    ```
    
    The issue still happens

**Comment by kevzettler** [comment]
@philpax I just switched to `ambient_api = "0.2.1"` and did `cargo update`

```
/Users/kevzettler/code/ambient-test-project
kevzettler@kevs-mbp-3 ambient-test-project % cargo update
    Updating crates.io index
      Adding ambient_api v0.2.1
      Adding ambient_api_core v0.2.1
      Adding ambient_api_macros v0.2.1
      Adding ambient_cb v0.2.1
      Adding ambient_color v0.2.1
      Adding ambient_editor_derive v0.2.1
      Adding ambient_element v0.2.1
      Adding ambient_element_component v0.2.1
      Adding ambient_friendly_id v0.2.1
      Adding ambient_guest_bridge v0.2.1
      Adding ambient_math v0.2.1
      Adding ambient_project v0.2.1
      Adding ambient_project_macro_common v0.2.1
      Adding ambient_project_rt v0.2.1
      Adding ambient_schema v0.2.1
      Adding ambient_shared_types v0.2.1
      Adding ambient_time v0.2.1
      Adding ambient_ui v0.2.1
    Updating libc v0.2.143 -> v0.2.144
    Updating quote v1.0.26 -> v1.0.27
    ```
    


unfortunately    The issue still happens

**Comment by philpax** [comment]
Cheers, will look into it!

**Comment by philpax** [comment]
Had some time to look at it, and realised what the issue was.

The proc-macro is only built if R-A sees a binary using it; however, because the `client` and the `server` binaries both have `required-features`, R-A doesn't consider them, and doesn't end up building the proc macro.

To fix this, you need to tell your IDE/R-A to treat the environment as having those features enabled, so that it will attempt to build the binaries and the corresponding proc macro. We have this set up by default for new projects, but it's something that needs to be added to existing projects.

To do this for VSCode (sorry, not sure what it is for emacs), create `.vscode/settings.json` in your project directory:

```json
{
  "rust-analyzer.cargo.features": ["client", "server"]
}
```

Sorry about this - we should have called this out in the changelog!

Let me know if that fixes the issue.

**Comment by kevzettler** [comment]
ok thanks that was the issue. Found an emacs implementation at:
https://github.com/emacs-lsp/lsp-mode/issues/3375

**Comment by philpax** [comment]
Can you detail what settings you used for emacs? I'll add both VSCode and Emacs to the known pitfalls docs

**Comment by kevzettler** [comment]
ok I just had to revisit this after some updates and the I had to set the following variables for `lsp-mode` in emacs

```
  (setq lsp-rust-analyzer-cargo-target "wasm32-wasi"
        lsp-rust-analyzer-cargo-watch-args ["--features" "client server"]
        lsp-rust-features ["client" "server"])
```

**Comment by kevzettler** [comment]
Furthermore you can add a `.dir-locals.el` file to your project directory that emacs will pick up and load settings for. Similiar to the `.vscode/settings.json` The contents of that file in my project are:

```
((rustic-mode . ((eval . (setq-local lsp-rust-analyzer-cargo-target "wasm32-wasi"))
                 (eval . (setq-local lsp-rust-analyzer-cargo-watch-args ["--features" "client server"]))
                 (eval . (setq-local lsp-rust-features ["client" "server"])))))
```

**Comment by FredrikNoren** [comment]
@kevzettler Would you mind adding this to https://ambientrun.github.io/Ambient/user/setting_up_ide.html ? We should create a section for emacs there
