### ISSUE TITLE
UI update causes modification of client side transforms/entity hierarchy

### ISSUE THREAD

**Issue by devjobe** [AmbientRun/Ambient#378]
I encountered a bug where using a UI hook would modify transform of the prefab model instance.

[Video](https://github.com/AmbientRun/Ambient/assets/71590722/0f1e76ca-a6d4-4ac9-a721-2fea4ffb4543)

I believe it is forcing some update from server causing the child-parent relationship be modified.

Repo Branch: https://github.com/devjobe/ambient_third_person_character/tree/TransformBug

Spawning prefab on client bugs:
https://github.com/devjobe/ambient_third_person_character/blob/917cfddb26fce3da75059ae7548987cc321a1652/src/client.rs#L30

Moving it to server side works:
https://github.com/devjobe/ambient_third_person_character/blob/917cfddb26fce3da75059ae7548987cc321a1652/src/server.rs#L18

I believe animation controller is innocent it's just causing the transforms to be updated. Nothing happens when it's removed due to the transforms not being touched by anything.

**Comment by philpax** [comment]
@FredrikNoren one for you when you get back

**Comment by FredrikNoren** [comment]
Hm that's bizarre. @devjobe can you try dumping the client side ecs before and after it breaks, and then run a diff on them to see what changed?

**Comment by devjobe** [comment]
I don't know when but I can get to it eventually if you want to assign it to me. It's just not a priority for me since I can spawn it on server side and I've more urgent things to deal with atm. thesis is top prio until monday atleast.

**Comment by FredrikNoren** [comment]
@devjobe Thanks, assigned

**Comment by chaosprint** [comment]
this has nothing to do with UI update I guess. I got this when there is no UI at all

**Comment by FredrikNoren** [comment]
@VinhTruongAmbient Is taking a look, we suspect it's got something to do with gpu ecs or gpu mesh buffers. There's a minimal example here: https://github.com/AmbientRun/fbxbug/tree/main
