### ISSUE TITLE
Use Rust-native code to transcode audio in the audio pipeline

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#38]
At present, we shell out to `ffmpeg` to transcode audio to `ogg`. To reduce the dependency on external utilities (especially on Windows), we should consider using the `symphonia` crate to decode all supported audio formats, and then encode it with one of the `ogg` encoding crates.

**Comment by marceline-cramer** [comment]
Hey, I want to let everyone know that I've already started working on this and will have a PR for it soon.
