### ISSUE TITLE
`CursorLockGuard` doesn't handle exceptional cases well

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#386]
As mentioned by @ten3roberts - the `CursorLockGuard` is both too sensitive (it will lock at the slightest input) and not sensitive enough (it will not handle window switching or OS cursor theft).

To fix this, we should make it only lock on mouse-click (and maybe some keyboard input), and we should also make it listen to OS cursor theft. Alternatively, we can have it attempt to lock every frame if there's input actively being driven to the game, which is apparently what Unity does?

**Comment by ten3roberts** [comment]
To be specific.

Unity does not capture the mouse on input automatically, that is something the user has to set up in thier `GameManager::Update` monobehavior

**Comment by ten3roberts** [comment]
Additionally, when ambient is launched the cursor will get locked without the user having to click on the window.

This causes the cursor to get locked and hidden *outside* the window.

The the user presses a mouse button the cursor will click on the app behind and bring it to the front, losing ambient which never got the click.

Repositioning the cursor to be *on* the window is cumbersome due to the other issues with the cursor lock guard, and often requires `alt+tabbing` out of the application, positioning your cursor where the ambient should be, and then tabbing into ambient.

I do believe that this workaround and issue is unnecessary and not good to have since it is one of the first things a new user will encounter, and is as such not a good first impression.

**Comment by ten3roberts** [comment]
In `afps` pressing escape does not unhide or free the cursor.

Additionally, if you click on the window using the mac dock shooting will still click the application the dock. I've managed to reproduce it by other means as well (alt-tabbing) and it happens as well. Have so far managed to turn on dictation, close firefox tabs, and maximize ambient itself.

**Comment by ten3roberts** [comment]
Additionally, there seems to be further issues with the input as it is sometimes missed.

I can reproduce this most easily if you press *and* unpress a key within the same frame. This means that if you have a low framerate (by e.g being on a Mac) clicks and key presses are occasionally missed, with an probability exhibiting an inverse relation to your framerate

**Comment by philpax** [comment]
> In `afps` pressing escape does not unhide or free the cursor.

I wasn't able to reproduce this. Can you upload a video?

> Additionally, if you click on the window using the mac dock shooting will still click the application the dock. I've managed to reproduce it by other means as well (alt-tabbing) and it happens as well. Have so far managed to turn on dictation, close firefox tabs, and maximize ambient itself.

Yeah, it doesn't snap your cursor back into the window when you do this. That's not the best - I suppose we could have the call to grab(true) move the cursor back to the centre?

> Additionally, there seems to be further issues with the input as it is sometimes missed.

I think that's been around for a while. Maybe we should run input capture in another thread and send all of them to be processed in one logic tick? I'm not entirely sure what the behaviour would be there, though - if I press-and-release a key five times in 16ms, does it get treated as one press, or five? I'm not sure the latter is possible because WASM is tied to each frame :/

**Comment by ten3roberts** [comment]
Sure thing, here is a video as of 8ffc355

https://github.com/AmbientRun/Ambient/assets/25723553/ecf6641d-490c-4741-a3c1-6eae2d301b89

**Comment by ten3roberts** [comment]
Yes. The input issue can be reproduced by running the ~4 fps music visualizer. Left clicking results in nothing happening half the time, and another quarter of the time you click the wrong square because the position is not updated before click is handled.

Can you reproduce *that*?

**Comment by ten3roberts** [comment]
> Yeah, it doesn't snap your cursor back into the window when you do this. That's not the best - I suppose we could have the call to grab(true) move the cursor back to the centre?

For other projects I've found that hiding (and not moving the cursor back to the window) the cursor is sufficent as the OS will go "oh, I see the cursor is not visible, in that case clicking on *something* is meaningless so I will instead just feed them to the focused window".

**Comment by ten3roberts** [comment]
> I think that's been around for a while. Maybe we should run input capture in another thread and send all of them to be processed in one logic tick? I'm not entirely sure what the behaviour would be there, though - if I press-and-release a key five times in 16ms, does it get treated as one press, or five? I'm not sure the latter is possible because WASM is tied to each frame :/

The usual approach is to treat inputs such as these as a channel, and not a lossy signal as we do now. We could build up a queue of a fixed size and error if the queue is full (e.g 128 should be enough). The wasm will then be able to drain that queue each frame.

What we have now is essentially a `tokio::channel::watch` channel, which is not good as intermediate values *are* significant

**Comment by philpax** [comment]
> Sure thing, here is a video as of [8ffc355](https://github.com/AmbientRun/Ambient/commit/8ffc35538acf874a8b5fdad890cde77367333bd4)
> 2023-07-21.11-17-05.mp4

It looks like that's the cursor staying in the dock, while the cursor has been grabbed by Ambient. My guess is the cursor is being made visible by macOS. The input is still being released and grabbed by Ambient when it should be.

> Yes. The input issue can be reproduced by running the ~4 fps music visualizer. Left clicking results in nothing happening half the time, and another quarter of the time you click the wrong square because the position is not updated before click is handled.
> 
> Can you reproduce _that_?

Yes, the input is being dropped because the client isn't running fast enough to capture the input. That's not related to the original input lock issue, is it?

> For other projects I've found that hiding (and not moving the cursor back to the window) the cursor is sufficent as the OS will go "oh, I see the cursor is not visible, in that case clicking on _something_ is meaningless so I will instead just feed them to the focused window".

The cursor is hidden when input is grabbed, which is why I think macOS itself is unhiding it here.

I think the easiest solution really might just be moving the cursor on grab.

> The usual approach is to treat inputs such as these as a channel, and not a lossy signal as we do now. We could build up a queue of a fixed size and error if the queue is full (e.g 128 should be enough). The wasm will then be able to drain that queue each frame.

I have considered this, but as far as I'm aware, other game engines don't actually do this. Do you have any examples of how this works in other engines?

**Comment by ten3roberts** [comment]
> Yes, the input is being dropped because the client isn't running fast enough to capture the input. That's not related to the original input lock issue, is it?

It sortof is, as it prevents the escape key from working

**Comment by ten3roberts** [comment]
> The cursor is hidden when input is grabbed, which is why I think macOS itself is unhiding it here.

In the second half of the window you can see that the cursor is not hidden when using cmd-tab, and I can click the terminal below

**Comment by philpax** [comment]
> > The cursor is hidden when input is grabbed, which is why I think macOS itself is unhiding it here.
> 
> In the second half of the window you can see that the cursor is not hidden when using cmd-tab, and I can click the terminal below

Right, good point. Turns out macOS will just show the cursor, even if it's grabbed, if it's outside of the window. I've added code to move the cursor on grab in https://github.com/AmbientRun/Ambient/commit/2cfe2fb93c40f73df8a6191053c7e86d7638de43 and it seems to consistently fix this issue for me (cmd+tabbing and dock-entry both hide the cursor as required.)

Can you test and check if that resolves it?

> > Yes, the input is being dropped because the client isn't running fast enough to capture the input. That's not related to the original input lock issue, is it?
> 
> It sortof is, as it prevents the escape key from working

I'll see if I can queue up inputs and fire off relevant events somehow...

**Comment by philpax** [comment]
> > > Yes, the input is being dropped because the client isn't running fast enough to capture the input. That's not related to the original input lock issue, is it?
> > 
> > 
> > It sortof is, as it prevents the escape key from working
> 
> I'll see if I can queue up inputs and fire off relevant events somehow...

Ok, I think this might be non-trivial; I think we'd have to decouple the logic/rendering from the winit loop. I'm going to close this issue and resurrect one of the older input issues if that's OK with you?

**Comment by philpax** [comment]
I'm closing this in favour of #614, which more accurately describes the issue at hand.
