### ISSUE TITLE
ambient_ui docs are not working

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#403]
This page reports that the docs failed to build: https://docs.rs/crate/ambient_ui/0.2.1

**Comment by philpax** [comment]
Damn. Same issue as the 0.2.1 blocker:

https://github.com/AmbientRun/Ambient/commit/a18756e9f026c7abf3c099027b8de16696868de7

Let's add that to all the doc-able crates, I guess

**Comment by FredrikNoren** [comment]
Also when clicking `ambient_cb` in the api docs we're brought to another erroring page: https://docs.rs/ambient_cb/0.2.1/ambient_cb/?search=index.html . Same with `ambient_editor_derive`

**Comment by philpax** [comment]
That might be an actual docs.rs bug - we'll want to ask them.
