### ISSUE TITLE
Naming: `screen_to_world_direction` and `clip_space_ray`

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#410]
Was a bit confused first, thought it would be just the direction part (just a Vec3) for `screen_to_world_direction`, and `clip_space_ray` doesn't contain "world" so seems like the ray is in clip space from the name. 

Perhaps `screen_pos_to_world_ray` and `clip_pos_to_world_ray`?

**Comment by philpax** [comment]
Fine by me, the only thing I'd change is `pos` -> `position` (we avoid shortenings where possible to make it less ambiguous) or removing the `pos` entirely
