### ISSUE TITLE
Blender Animation transforms are off on Ambient import

### ISSUE THREAD

**Issue by kevzettler** [AmbientRun/Ambient#419]
I have a rigged and animated character in Blender. I'm exporting as gltf/glb. The pose keyframes are getting transformed weirdly when the get to ambient.

Here's an example of the 'idle' pose. Which is one keyframe

## Idle
* Blender
<img width="251" alt="image" src="https://github.com/AmbientRun/Ambient/assets/126209/6bb8369a-8b6f-4467-90db-05eb13cec418">

* Ambient
<img width="912" alt="Screen Shot 2023-05-23 at 2 05 20 PM" src="https://github.com/AmbientRun/Ambient/assets/126209/109c8d64-405a-44b9-b690-d0f53334c490">

You can notice the shoulders and knee joints are kinked and off and the hitbox is not bound to the hand.

## Walk
* Blender
![walk](https://github.com/AmbientRun/Ambient/assets/126209/4ad8b403-e03d-40c4-9232-07d291c22752)

* Ambient
![walkAmbient](https://github.com/AmbientRun/Ambient/assets/126209/4db778ec-9263-42e2-ad07-548efa064d5a)

How can I further troubleshoot this? I just redid the rig and animations and maybe missed baking some transforms.

you can find the code at https://github.com/kevzettler/ambient-test-project/tree/new_animations on the `new_animations` branch

**Comment by FredrikNoren** [comment]
Hm can you try opening the glb in another program to verify it works? I’ve used this before : https://gltf-viewer.donmccurdy.com/ (you can just drop the model on the website there to verify it)

**Comment by kevzettler** [comment]
# gltf-viewer
*idle
![image](https://github.com/AmbientRun/Ambient/assets/126209/d4e6318f-cced-4be4-9410-486e88737a2b)
*walk
![walkdon](https://github.com/AmbientRun/Ambient/assets/126209/bb68d527-a24e-48d6-9bfe-bd06851e4094)

The poses in glTF Viewer match the poses in Blender.

There appears to be some warnings related to skinned mesh nodes 

![image](https://github.com/AmbientRun/Ambient/assets/126209/4685b30c-1434-4fd2-91b4-046dfccf295a)

For sanity I also tried BabylonJS gltf viewer at: https://sandbox.babylonjs.com/

#Babylonjs
* Idle
![image](https://github.com/AmbientRun/Ambient/assets/126209/f12568ba-90b0-4a77-b3bd-a386984c48b1)
* Walk

![walkbab](https://github.com/AmbientRun/Ambient/assets/126209/ecd17a0b-8c95-4b84-ad3f-310b959ac97c)

Babylon also matches the Beldner animations

**Comment by FredrikNoren** [comment]
Hm might be related to the warnings; could be that ambient applies the transform of the skinmesh entity differently. Not entirely sure.

**Comment by kevzettler** [comment]
possibly related:
https://github.com/KhronosGroup/glTF-Blender-IO/issues/1626
https://github.com/KhronosGroup/glTF-Blender-IO/issues/1538#issuecomment-1015403354

Leaving as breadcrumbs for my  debugging.

**Comment by kevzettler** [comment]
@FredrikNoren I resolved the warnings and made a totally new rig+animations the issue persisted. Further information. It seems like this issue is non deterministic. I can wipe the build directory in my project and run it and it produces different animation transformations each time.

I can run a bunch of these commands in succession and get different animations
```
rm -rf ./build && ~/code/Ambient/target/release/ambient run
```

I've attached a video demonstrating me:
* run the command above
* move character to check walk animation
* close ambient window
* run command again

https://github.com/AmbientRun/Ambient/assets/126209/65d1c924-e416-426e-84bf-5b479eb973de

**Comment by FredrikNoren** [comment]
@kevzettler Hm that's interesting. Could you save the `build/assets/MODEL.glb/models/main.json` and `build/assets/MODEL.glb/animations/*` somewhere, re-run the build and use a diff tool to see if they are different between builds?

**Comment by FredrikNoren** [comment]
@kevzettler Can you try this with the new animation api; there's an `apply_base_pose` function on the `PlayClipFromUrlNode` which you can set to true.

**Comment by kevzettler** [comment]
For a sanity test I tried exporting an FBX file from Blender instead of glb. I'm seeing the same behavior. Every-time I run `ambient run` the pose and animation transforms are non deterministically mutated

Fbx branch is:
https://github.com/kevzettler/ambient-test-project/tree/fbx_animations

**Comment by FredrikNoren** [comment]
@kevzettler Ok I think I've figured out what's going on; there are two entities with the same name for a lot of entities. For instance, I see two `forearm.L`. The bind_id's are the components that decide which entity gets updated by which animation; the animation might have an output like `bind_id: forearm.L`, but since there are two of those, it becomes random which one is selected.

**Comment by FredrikNoren** [comment]
(Though, I think this is a bug with ambient; since other programs can handle it, we should be able to too)

**Comment by kevzettler** [comment]
@FredrikNoren ok good find. I do have multiple corresponding things named the same. like :
Bone: forearm.L
Mesh: forearm.L
Vertex Group: forearm.L

**Comment by FredrikNoren** [comment]
@kevzettler Alright the fix is merged now, please re-open if it's still not working for some reason.

Nice model btw!

**Comment by FredrikNoren** [comment]
Oh an re the bind_id's looked up by unique identifier; yeah that would be more robust in this case, but it doesn't work when you want to do retargeting (using an animation from one character for another character), which is why it's using the "semantic" names.
