### ISSUE TITLE
Return feedback from asset pipeline when building Ambient project

### ISSUE THREAD

**Issue by ghost** [AmbientRun/Ambient#436]
Calling `ambient run` on a project with an asset pipeline returns:

```
[2023-05-29T06:36:58Z INFO  ambient] Building my-project
[2023-05-29T06:36:59Z INFO  ambient] Done building my-project
```

I think it is a better user experience to communicate a bit more about what is currently happening. This problem gets worse as the number of assets grow, since the program will appear to be frozen while importer is running.

**Comment by philpax** [comment]
This is a duplicate of https://github.com/AmbientRun/Ambient/issues/219, but that hasn't been done yet.

I wonder if there's a way to combine one of the spinner libraries with logging, so that you can see an inline percentage of build progress.

**Comment by VinhTruongAmbient** [comment]
https://crates.io/crates/indicatif is a great crate for communicating progress.

**Comment by philpax** [comment]
Closing in favour of #219.
