### ISSUE TITLE
Panic typos in `pipeline.json` during building

### ISSUE THREAD

**Issue by chaosprint** [AmbientRun/Ambient#439]
Currently, there won't be any error report if there is a typo in
```
{
    "pipeline": {
      "type": "Models",
      "colliders": {
        "type": "fromModel"
      }
    }
}
```
It will cause some unexpected behaviour and become hard to debug. Perhaps we should make it panic if the entry is not supported.

**Comment by ten3roberts** [comment]
Do you have a repro repo?

I can't reproduce it locally, it panics if it is incorrect

**Comment by ten3roberts** [comment]
The issue is not that `FromModel` is mistyped to `fromModels` (stated externally on discord) but rather that `collider` is typed as `colliders`. Our deserialization will ignore unknown fields and thus ignores `colliders` and uses the default value for `collider`

**Comment by ten3roberts** [comment]
Plural suffix the schema strikes yet again
