### ISSUE TITLE
build/assets folder ends up in the wrong place if there are spaces in the path

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#464]
repro: Move the `asset_loading` example into a folder that has spaces in its name, delete the build folder, then cd inside the project and call `ambient build`.

If the folder structure is `Parent Folder/asset_loading` then the built assets will not go to `Parent Folder/asset_loading/build/assets` but instead to `Parent Folder/Parent Folder/asset_loading/assets`

cc @ten3roberts

**Comment by ten3roberts** [comment]
And here I thought we would be safe from these issues using Rust...

**Comment by ten3roberts** [comment]
To clarify, occurs on mac as well.

The parent folder(s) has to contain spaces, not the project name/folder for it to break

**Comment by ten3roberts** [comment]
Having a space inside our guest examples also panics any other ambient run as it results in an invalid workspace configuration due to the stray directory which isn't a rust crates/Cargo.toml.

This specific issue is addressed by #470
