### ISSUE TITLE
Text rendering broken

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#466]
Repro: start the fog example, pull the slider to 0, then move it up again, only the 0 is drawn. There's another mesh with the ".534" part which isn't visible. This all used to work.

I did a git bisect, this is the commit that breaks it: https://github.com/AmbientRun/Ambient/commit/5599f75cd4189acb04fd88a70f9d2c55181b67ee
I.e. https://github.com/AmbientRun/Ambient/pull/425

@VinhTruongAmbient Seems like we still have some text mesh rendering issues :)

**Comment by VinhTruongAmbient** [comment]
Looks like the removal of `primitives()` component was the problem. The actual operation we had to do is to _clear` it instead, not remove it. Creating a PR.
