### ISSUE TITLE
`skin_tracking` example is broken

### ISSUE THREAD

**Issue by chaosprint** [AmbientRun/Ambient#467]
no UI is shown. no tracking of course.

```
let binders = entity::get_animation_binder_mask(unit_id);
```
returns an empty array on the FPS game now.

@devjobe is this related to the changes you made days ago?

**Comment by devjobe** [comment]
@chaosprint I believe so, I think I'll have time later today to fix it

**Comment by FredrikNoren** [comment]
I've removed the skin_tracking example and added this to the skinmesh example, which I think demonstrates the same concept: https://github.com/AmbientRun/Ambient/blob/main/guest/rust/examples/basics/skinmesh/src/client.rs#L54
