### ISSUE TITLE
Add `egui` support for internal tooling

### ISSUE THREAD

**Issue by VinhTruongAmbient** [AmbientRun/Ambient#475]
The long-term goal is to develop our Ambient UI system to be powerful enough to be widely used. Meanwhile, there is a need for a reliable and well-featured GUI system specifically for development-time contexts, such as developing and diagnosing issues in the renderer. We currently think `egui` is an excellent first candidate for such a tool.

**Comment by FredrikNoren** [comment]
So we discussed this and the plan is to revert to egui if there's a specific case where egui can save us a large amount of work compared to the ambient ui, otherwise well dog food the ambient ui for internal tools too.
