### ISSUE TITLE
`character_controller_height`, `character_controller_radius` should be given together

### ISSUE THREAD

**Issue by chaosprint** [AmbientRun/Ambient#480]
The doc says:

> If an entity has both this and a character_controller_radius, it will be given a physical character collider.

If the guest developer provides only one of them, it should not compile.

Perhaps it should also panic, if `[physics_controlled]` is absent.

there are some other contexts in which we may want to reject some components. For example, sometimes it doesn't make any send to use a `dynamic` but the code will compile while nothing will happen.

**Comment by chaosprint** [comment]
Perhaps we can use `ensure_has_component`?

**Comment by FredrikNoren** [comment]
So the "concepts" were kind of aiming at solving this, but I think there's still room for improvement.

I ran into the same problem when doing the new animation system; I've added structs to the guest api which are just wrapping EntityId's, just to make them "strongly typed": https://github.com/AmbientRun/Ambient/blob/main/guest/rust/api_core/src/animation.rs

@philpax let's have a chat about this once you're back.
