### ISSUE TITLE
Add a way to download asset binary data to the guest

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#506]
Something like:

```rust
let data = asset::read(asset::url("my_texture.png")).await;
```

Meanwhile, users _can_ use `include_bytes!("build/assets/my_texture.png")`, although it's not ideal to bundle the content with the executable

**Comment by philpax** [comment]
This should work on both the client and server.

**Comment by pierd** [comment]
We should secure opening arbitrary URLs from server at least for servers running in our infra.

**Comment by philpax** [comment]
Hmm, yeah, probably. What restrictions are you thinking of?

**Comment by pierd** [comment]
I'd allow any downloads from `https://assets.ambient.run/`. For anything else I'd at least rate limit it if not disallow completely.

**Comment by philpax** [comment]
Rate limit sounds like a good idea. I'd like it to be able to call out to external APIs (authentication, data retrieval, AI, etc) but we also don't want to make a free DDoS machine.
