### ISSUE TITLE
Descriptive error message for invalid types in components and message fields

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#538]
```
[messages.player_command.fields]
mvx = { type = "I8" }
mvy = { type = "I8" }
```

The error message that results from this message field definition (in ambient.toml) is currently the following:

```
called `Result::unwrap()` on an `Err` value: invalid primitive type
```

Instead it should say something like this:

```
Message field type definition in ambient.toml (line 7) is invalid (type "I8" is unsupported by Ambient protocol)
```

As many of the below as possible, to assist the user in understanding the user error aspect of the issue, so that they can resolve it quickly by themselves

- Refer to problematic filename (e.g. 'ambient.toml')
- Refer to line number in file (not that important, but nice if it is possible)
- Describe the problem at the user error level (e.g. 'message field type definition is invalid') rather than in terms of the backend problem (i.e. I have not written any `Result::unwrap` code so I have no idea what it is referring to, or how to fix it)
- Use language that indicates that the issue is not a bug, but known and intentional ('unsupported by Ambient')

**Comment by chaosprint** [comment]
related here: https://github.com/AmbientRun/Ambient/issues/524#issuecomment-1600939634

**Comment by ten3roberts** [comment]
All these bullet points are possible to one extent or another.

Returning the line of the error is something we already do in some places (like pipeline custom components) and is really only limited by the toml parser.

The issue is that the chain stops and slams into a wall where it can't peek through if we don't support it all the way through, which js why you gets the "hand waving: somewhere around here"

**Comment by philpax** [comment]
This is improved with #417:
```
[ember]
id = "dependencies"
organization = "ambient"
name = "dependencies"
version = "0.0.1"

[messages.hello]
name = "Hello"
fields = { text = "i8" }
```
results in
```
Error: Failed to resolve type `i8` for field `text` of message `hello`
```
It would be nice to get a filename and line number in there. I'll see what I can do at some point...
