### ISSUE TITLE
Do not show run errors that result from build errors (?)

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#539]
If I write a bad message field in my `ambient.toml` file, it causes `run` to fail with an error message.

(I opened a separate issue regarding that error message: https://github.com/AmbientRun/Ambient/issues/538)

However, it also produces an _additional_ error message which confuses the problem as a dev trying to understand the mistake I've made, because it is not the root of the problem:

```
error[E0601]: `main` function not found in crate `client_w_02_broughlike`
```

In fact it makes a very misleading suggestion:

```
   |
32 | }
   |  ^ consider adding a `main` function to `w02-broughlike\src/client.rs`
```

I believe this message appears in various contexts where something causes the build to fail. It's easy enough for me to ignore now that I know what I'm looking for but if we can avoid displaying this type of superfluous error message it will help new users' debugging efforts in the future.

**Comment by philpax** [comment]
I've done my best to fix this, but I'm afraid it's still a bit noisy :(

We don't have too much control over the display output - we can't tell it to not show warnings, for example, when there's a macro failure. I'll see if there's anything we can do to cut this down further, but I suspect this is where it'll be stuck for a while.
