### ISSUE TITLE
Don't synchronize entities with no networked components

### ISSUE THREAD

**Issue by marceline-cramer** [AmbientRun/Ambient#562]
I have a very large number of server-side entities that I spawn to do server-side game logic with the entire world state. Because of the massive amount of network bandwidth that would be required to synchronize the entire world state to every client using Ambient's built-in ECS sync, I've opted to use manual client messaging to synchronize select parts of the world to different players (in stead of #492). However, my server-side entities that have only non-networked components for server logic are getting spawned (without those components) on each client, resulting in *thousands* (and as the game gets larger, eventually *millions*) of empty entities that have been unnecessarily synchronized.

It's essential that the server only synchronizes entities to clients if those entities have a non-zero number of networked components.

**Comment by marceline-cramer** [comment]
@ten3roberts mentioned that there was a host-side `no_sync` component that could be added to entities in order to disable their network synchronization. If disabling empty network sync isn't an option, exposing `no_sync` or a similar component to the guest would be the next best thing. Either way, I'm going to need to oust those empty entities from the network bandwidth if I'm going to be able to make large worlds in Flowerpot.

**Comment by ten3roberts** [comment]
The streaming should ignore "empty" entities as well, so I wonder if we have a system which attaches some small innocuous component automatically and causing all the entities to be streamed over.

Would you be able to dump the whole server hierarchy and share it to see if there is any such component?

**Comment by marceline-cramer** [comment]
@ten3roberts here's one!

Sorry for the huge amounts of cruft, I'm working to pare down the entity count.
[server_hierarchy.tar.gz](https://github.com/AmbientRun/Ambient/files/12088891/server_hierarchy.tar.gz)

**Comment by ten3roberts** [comment]
Could you dump the client hierarchy as well? And perhaps create a smaller map to test it with to reduce the file size?

Thanks

**Comment by marceline-cramer** [comment]
So sorry for the delay, this has slipped my mind.
[hierarchies.tar.gz](https://github.com/AmbientRun/Ambient/files/12331083/hierarchies.tar.gz)

**Comment by marceline-cramer** [comment]
I agree.
