### ISSUE TITLE
with_default on Bool components should set them to "true"

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#576]
Generally a false Bool component is the same as not having it.
This will bring the behaviour of Bool/None components more in line with each other, i.e. with_default will do closer to the same thing for both of them.

**Comment by philpax** [comment]
This is in line with Rust's behaviour for `Default`: https://doc.rust-lang.org/src/core/default.rs.html#203

It also appears to be the default in C#: https://stackoverflow.com/questions/6855664/what-is-the-default-boolean-value-in-c

I think we're just following convention here. Do you know of any other ecosystems where the default is true?

**Comment by droqen** [comment]
The default value `false` is definitely conventional... Possibly the beef I have is better addressed by questioning the `Empty` component type. I'll close this in favour of the other issue.
