### ISSUE TITLE
Guest examples testing network reliable streams

### ISSUE THREAD

**Issue by ten3roberts** [AmbientRun/Ambient#590]
There are currently none, or at least few guest examples which tests sending reliable (uni/bi) streams from the server to the client.

@chaosprint stumbled upon that it had a bug some time ago, but we still don't have a way to ensure it does not regress.

Modifying an example to send data back reliable would be enough, I think you @philpax would know the examples best and which one to augment

**Comment by philpax** [comment]
This would be interesting, but I'm not sure how we'd do it. Have the `messaging` send a message from side A to side B, have side B send a message back, and check that we get the message back within a second?

**Comment by ten3roberts** [comment]
I think we could just use the messages to spawn client side and server side models, and use the golden images to verify that they are there. The timing is not important as long as they arrive before the AU timeout.

Right now, the examples use only datagrams for this

**Comment by philpax** [comment]
Just did that and it looks good - thanks for the idea 🚀
