### ISSUE TITLE
Guest-side UI should be able to manipulate the clipboard

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#591]
I'm planning on adding clipboard manipulation functions (get/set) so that the UI can use these to populate from clipboard/populate to clipboard. This is a *little* controversial as server hosts could potentially use this to spy on users and exfiltrate their clipboard data, but not being able to paste into a UI element isn't very convenient, either...

**Comment by ten3roberts** [comment]
Have a look inside `ambient_sys::clipboard` I've started on the set functionality
