### ISSUE TITLE
`hooks.use_query((player())` holds players who left

### ISSUE THREAD

**Issue by chaosprint** [AmbientRun/Ambient#607]
Reproduce:
- `ambient run` https://github.com/AmbientRun/afps
- `ambient join`
- then CTRL-C to exit
- open the scoreboard by holding the Tab key; the player that left still remains

**Comment by ten3roberts** [comment]
There is an issue where joining through the proxy won't time out the player if they don't properly disconnect.

Does it only occur through the proxy, or locally as well, and does the player entity/model despawn?

**Comment by chaosprint** [comment]
> There is an issue where joining through the proxy won't time out the player if they don't properly disconnect.
> 
> Does it only occur through the proxy, or locally as well, and does the player entity/model despawn?

Locally as well. Model still remains.

**Comment by ten3roberts** [comment]
If you kill or CTRL-C the app it will take ~2 minutes for the player model to disappear, unless `AMBIENT_DISABLE_TIMEOUT=true` in which case it will never occur.

How long did you wait?

**Comment by chaosprint** [comment]
> If you kill or CTRL-C the app it will take ~2 minutes for the player model to disappear, unless `AMBIENT_DISABLE_TIMEOUT=true` in which case it will never occur.
> 
> How long did you wait?

The player list got update in around 1 min. But the shadow of the model seems to remain there forever even though its collider is gone in 1 min.

<img width="912" alt="image" src="https://github.com/AmbientRun/Ambient/assets/35621141/906df557-eb71-4bd2-aa71-9690e4682949">

**Comment by philpax** [comment]
Can you check if the symptoms of this still occur after #622 ?

**Comment by philpax** [comment]
That sounds like the desired behaviour; can we close this issue?

**Comment by chaosprint** [comment]
> That sounds like the desired behaviour; can we close this issue?

yes!
