### ISSUE TITLE
Fixed framerate tick subscription on the client

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#610]
At present, the `Frame` event on the client will run every frame (as the name suggests); however, this will lead to a) unnecessary work (more simulation than is strictly necessary) and b) unnecessary network traffic (code that sends updates every frame will lead to queue backpressure on the server)

We should offer a fixed rate tick that only runs every 1/60th of a second (or whatever rate we pick, perhaps server-specified, but we probably don't want it to be a parameter server owners tweak without understanding?)

Open questions:
- What should the tickrate be?
- What happens when the client drops below that tickrate?
- What happens when it drops just below, so that you have the worst-case scenario of having to wait another full tick again?
- Should developers expect that frametime to be constant, or should they still need to use `delta_time()`?

**Comment by pierd** [comment]
Experienced it on macOS when:
- running on different displays (120fps on builtin, 60fps on external)
- minimising the app - immediately jumps to 600-700fps
- running with `--headless` - also jumps to hundreds of fps

**Comment by philpax** [comment]
I added `fixed_rate_tick` to the API some time ago. The answers to the questions posed above are:

1) Up to the user.
2) It's a simple `if (time() - last) > duration` implementation, so it'll run on the next frame.
3) Yeah, that sucks. Not much we can do about it.
4) `fixed_rate_tick` returns the elapsed time for developers to use.

We can revisit this if those nuances become an issue.
