### ISSUE TITLE
`EnitityId` is serialized as a base64 encoded string on the wire

### ISSUE THREAD

**Issue by pierd** [AmbientRun/Ambient#628]
Internally it's just `u128` so we are artificially creating 29 bytes out of 16.

**Comment by ten3roberts** [comment]
I do believe it was like this originally to aid debugging when viewing the serialized world as a file or through logs.

It also helps when comparing network traffic with other sources such as the ecs debugger as entity IDs Debug impl uses the same representation.

**Comment by pierd** [comment]
I've been looking into how we are using entity ids. And I'd like to make them smaller or at least smaller on the wire.

From what I've seen we can kind of split entity ids into 3 groups depending were they originate from:
1. Generated during build and stored in asset descriptions (for example in main.json in models and prefabs).
2. Generated on the server.
3. Generated on clients.

Is it correct that entities originating from the client (3.) are never shared with the server or other clients?
Assuming that most of the entities referenced on the wire are going to be the ones generated on the server (2.), I'd like to use sequential ids for them and use [VarInt encoding](https://docs.rs/bincode/1.3.1/bincode/config/struct.VarintEncoding.html). This would shorten most entity ids on the wire from 29 bytes to <5 bytes.

**Comment by FredrikNoren** [comment]
@pierd Sequential won't work, because they need to be creatable distributed (i.e. you can create an id on the client). We had generational before (kind of like sequential), but switched for that reason. Here's the issue where I was working on the switching: https://github.com/AmbientRun/Dims/issues/543
