### ISSUE TITLE
`ambient new` does not accept numerals

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#639]
```
PS C:\Users\hi\Repos\23-08Blue\Sketchbook> ambient new ss00-physics-momentum-err  
Failed to create project: each segment of an identifier must start with a lowercase ASCII character
```

The rule that 'each segment . . . must start with [a-z]' is alright, but it seems to be triggering at incorrect times. I've noticed that `ambient new` appears to create an id by separating letters from numerals - e.g. `w00_test` becomes `w_00_test`.

It was a sort of minor oddness before but now it appears the behaviour is blocking numerals from being accepted at all by the command regardless of where they are placed.

**Comment by philpax** [comment]
Yeah, the crate we use for case conversion assumes that numbers are breaking by default. Can be a bit embarrassing at times!

Was this on `main` or `enum-support`? (guessing the latter, but just confirming)

**Comment by droqen** [comment]
Yes, `enum-support`
