### ISSUE TITLE
mutating `linear_velocity()` causes problems with gravity and collisions

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#641]
```
    query(driven_power()).each_frame(|driven_bodies|{
        for (body,power) in driven_bodies {
            // (!!!) at any nonzero value, this cancels out gravity
            // (!!!) when moving into collision, this causes weird behaviour
            entity::mutate_component(body, linear_velocity(), |linvel|linvel.x -= power * delta_time());
        }
    });
```

See ember here
(P.S> please note it has as dependency another ember in the same repo, in a different folder, so you really need the whole thing)
https://github.com/droqen/23-08Blue/tree/main/Sketchbook/saa-physics-momentum-err

gif of `saa-physics-momentum-err` illustrating the problem:
![mut_linvel_glitch](https://github.com/AmbientRun/Ambient/assets/5104632/76f277a7-f486-4698-9cef-1b197f0e5773)

**Comment by droqen** [comment]
There are actually two separate problems being illustrated

1. When `linear_velocity` is being mutated each frame, it seems to prevent gravity from updating properly (but it does not _completely_ stop gravity)

2. When `linear_velocity` is being mutated each frame, it seems to override the effect a collision _should_ have on velocity (i.e. when moving into something, it should slow/stop your velocity, but here it seems to not to that)

I could not find any good examples of how physics objects are intended to be accelerated, so maybe I'm doing something wrong?

**Comment by droqen** [comment]
Hmm. I can probably close this. I found the functions in physics:: that I suppose I must be intended to use! Like `add_force`.

**Comment by droqen** [comment]
I'll leave this up for posterity - maybe there should be some kind of warning? Not sure.

**Comment by philpax** [comment]
Yeah, `linear_velocity` changes are discontinuous - you can't really update it every frame because the physics system needs to update it, too.

I've updated the description of the components in https://github.com/AmbientRun/Ambient/commit/4b173090a78ac3f7788f7769bf38d9aaf56ce94e - do you think that sufficiently clarifies the issue?

**Comment by philpax** [comment]
Shows up when you mouse over the component, or when you look at it in the API docs:
![image](https://github.com/AmbientRun/Ambient/assets/707827/425a372d-a3a3-4044-bb1f-38c90aece254)
<img width="568" alt="image" src="https://github.com/AmbientRun/Ambient/assets/707827/41b954b3-35a2-4e3c-ad67-d278c5570e61">
