### ISSUE TITLE
glTF not appearing in build output, with no diagnostics

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#644]
While testing #643, I tried using the glTF variant of the [same model](https://sketchfab.com/3d-models/phoenix-bird-844ba0cf144a413ea92c779f18912042), in the same place, with the same pipeline, and it didn't build while the FBX model did:
<img width="215" alt="image" src="https://github.com/AmbientRun/Ambient/assets/707827/f15a39fb-f499-4e43-9094-0c9b7ecb57cf">

There is no feedback in the build command:
```
mockingbird # ambient build
[2023-08-07T16:08:10Z INFO  ambient] Building project "mockingbird"

mockingbird # 
```

**Comment by chaosprint** [comment]
https://sketchfab.com/3d-models/low-poly-bird-animated-82ada91f0ac64ab595fbc3dc994a3590

this one, when downloaded as glb, works for me.

**Comment by FredrikNoren** [comment]
Don't think our loader works with gltf (they're often multi-file iirc.)

**Comment by philpax** [comment]
Yeah almost certainly (the model I tested with this didn't work), but at least the user has broken glTF instead of no output at all 🤷
