### ISSUE TITLE
latest enum-support - certain embers are broken? `ambient:bindings/component`

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#655]
See my project @ https://github.com/droqen/23-08Blue
Ever since switching to a 'workspace' and updating to the newest `enum-support` (I've remained on the bleeding edge pretty much every day), I can't run certain embers. I haven't been able to figure out why, but it can be (hopefully) easily reproduced.

`> ambient run blue-moon` successfully runs everything in blue-moon, but its dependencies, `ww_gen` and `a_nice_overhead_camera` both fail with the following error(s):
```
[2023-08-08T22:24:57Z ERROR ambient::client::wasm] [client_nice_overhead_camera] error: Runtime error: import `ambient:bindings/component` has the wrong type
    Root cause: expected record field named includes, found include
```

`> ambient run a_nice_overhead_camera` and `> ambient run ww_gen` individually also causes this error.

**Comment by philpax** [comment]
Try https://github.com/droqen/23-08Blue/pull/3 and see if that fixes it for you. I can get into the game with `blue-moon`, `ww_gen` and `a_nice_overhead_camera`, but I don't see anything with them, so you'll have to judge their correctness for yourself 😅

**Comment by philpax** [comment]
Is this sorted now?
