### ISSUE TITLE
ban `.with_default`

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#690]
Following discussion about Bool/Empty components here https://github.com/AmbientRun/Ambient/issues/577 I ceased using `.with_default` and have found it clears up a lot of footguns without really slowing down my workflow at all.

Components that use `Quat` and `Mat4` were initially slightly annoying but learning to type `Quat::IDENTITY` helped me to understand the codebase a little more, rather than hiding something so that I never understood it (or potential problems) in the first place. It's not a problem anymore, and the transition was a good one with basically no drawbacks for me.

I recommend not using `.with_default` at all, and changing at least the auto-generated `server.rs` code to not use it either.

**Comment by marceline-cramer** [comment]
My suggestion is to initially mark it as [deprecated](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute) so that users are pestered to use `.with` instead before later removing it entirely.
