### ISSUE TITLE
Unauthorized deploys generate Sentry alerts

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#740]
When I tried to deploy `afps_zombie` with the wrong API token, Sentry raised an alert and sent an email:
<img width="816" alt="image" src="https://github.com/AmbientRun/Ambient/assets/707827/be0684a4-2f44-463e-a222-3f3fceaa2bca">

**Comment by pierd** [comment]
Yeah, I am going to go through the errors reporting and decide which ones should actually be warnings/info logs instead.

**Comment by pierd** [comment]
Fixed but I'm going to monitor Sentry issues anyway.
