### ISSUE TITLE
Golden image tests may be timing out before they complete

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#749]
The golden image tests have started to fail again; looking at the resulting screenshots, the images are black. Our current hypothesis is that this is because we switched to debug builds for Ambient in the CI, and the failing tests (primarily messaging, but there are others) cannot finish their execution within the 30 second time limit.

I suspect it'd be resolved if we just doubled the timeout, but I'm not sure if that's the "best" fix per se.

**Comment by Pombal** [comment]
Fixed in https://github.com/AmbientRun/Ambient/commit/95b5d67653c7e9c20f140b5ad31d5a45c228b35d
