### ISSUE TITLE
Add an example of playing world audio

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#75]
Fairly simple: have a camera looking at a cube, the cube moves around with a looping sound attached to it, you can hear the sound moving with the cube.

Need to add functionality to play a sound from the server, which already exists in the platform and needs to be brought over. Not sure how to control looping / one-shot sounds with that API - would need @ten3roberts to explain.

**Comment by philpax** [comment]
For now, we'll just add a `repeat` parameter. Future work will involve https://github.com/KiwiOrg/Kiwi/issues/76.

**Comment by ten3roberts** [comment]
There is an example in dims `dims/examples/spatial.rs` which is very similar to what is described.

All that is needed is exposing audio graph apis in the wasm client, and moving the example code into a script, as it mostly just spawns things; something the client is more than capable of.

**Comment by philpax** [comment]
We released 0.1 without audio support, which gives us time to do #76 properly. I'll close this issue and explain what an example should have there.
