### ISSUE TITLE
Sign nightly build on OSX

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#761]
The build won't work unless it's signed. We should sign in the same way as the release build: https://github.com/AmbientRun/Ambient/blob/main/.github/workflows/release.yml#L71

**Comment by chaosprint** [comment]
@FredrikNoren It seems that some things need updating on Apple website for the secrets.
https://github.com/AmbientRun/Ambient/actions/runs/6019697844/job/16329874308

**Comment by FredrikNoren** [comment]
@chaosprint Think I've fixed it

**Comment by FredrikNoren** [comment]
I re-ran the build and seems to pass
