### ISSUE TITLE
Use nightly runtime version number in deploy

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#776]
The deployed package needs to say something like `ambient_version: "nightly-2023-08-31"` so that we know which ambient nightly build to download to run it with.

**Comment by pierd** [comment]
It will be for example `ambient_version: "0.3.0-nightly-2023-09-06"` if it's deployed with a nightly build. What should happen for deployments made with ambient from main branch? Should we completely disallow deployments using unknown versions?

**Comment by FredrikNoren** [comment]
@pierd Yeah let's do that. We need the runtime binary on the server side to run it so it doesn't make any sense to deploy with a local development version.

**Comment by pierd** [comment]
Deployed
