### ISSUE TITLE
Potential memory leak when running instancing example

### ISSUE THREAD

**Issue by pierd** [AmbientRun/Ambient#827]
Running instancing example in the cloud without any clients connected uses ~200MB RAM. One connected client bumps the memory usage to ~900MB, disconnecting doesn't bring that memory down. Connecting again increases the memory usage even more (eventually the server was killed).

![image](https://github.com/AmbientRun/Ambient/assets/752792/5943603b-bc86-41df-9d35-5a4f80d09506)

**Comment by pierd** [comment]
<img width="512" alt="Screenshot 2023-09-08 at 19 29 50" src="https://github.com/AmbientRun/Ambient/assets/752792/50ae1bc0-1824-45ce-a5cf-fd4a8c1eab30">

Might be something in the networking code as I've noticed a similar thing in afps after unclean disconnect (client crash).

**Comment by pierd** [comment]
Good news, the issue is with the diffs queue. When a player's bandwidth is not fast enough to receive all the updates, we queue them up while we send the previous one. That queue is held in raw format (not serialized and not even deduplicated or merged). With artificially limiting the bandwidth to 1MB/s (instancing requires about 7MB/s) I was able to reproduce having ~700MB worth of data in the queue for that player.

I'm planning to fix it by merging and serializing the diffs while the previous data is in flight.

**Comment by ten3roberts** [comment]
It's always the queues :smh:
