### ISSUE TITLE
UI mouse input on web is broken/offset

### ISSUE THREAD

**Issue by ten3roberts** [AmbientRun/Ambient#832]
It seems as if the UI code and window input does not take into account the offset of the canvas and assumes `0,0` means top-right of the canvas and not the browser window.

This effect is exacerbated by the ambient website which has a larger UI surrounding the canvas.

**Comment by FredrikNoren** [comment]
@ten3roberts This has been fixed right? Seems to work

**Comment by ten3roberts** [comment]
Yes, just forgot about and couldn't find the issue 😅
