### ISSUE TITLE
Ambient recompiles from `ambient_native_std` upwards every single time

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#835]
In the last few days, `cargo run` appears to need to recompile Ambient from `ambient_native_std` upwards, resulting in a miserable dev experience with a 30s wait each time at minimum.

I believe this may have been introduced with the merge of the web client, but we need to check. I have no idea what would cause this - is something being marked as dirty somewhere?

**Comment by FredrikNoren** [comment]
Hmm could it be because of the git_revision thing in there? git_revision_full

**Comment by FredrikNoren** [comment]
@pierd ^

**Comment by pierd** [comment]
I'll have a look if it's that or if I can spot anything else that's sus

**Comment by pierd** [comment]
@FredrikNoren Yip. `git_version!` macro is the culprit. I'm looking for a better way to solve this.
