### ISSUE TITLE
Web / desktop rendering discrepancies

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#836]
The water and sky do not render on the web. There may be others, but these are the most immediately obvious. I believe these are just a matter of wiring up the relevant systems and shaders.

Might also be a good chance to fix the texcoord wrapping on the water, now that I think about it.

**Comment by ten3roberts** [comment]
@philpax see: https://github.com/AmbientRun/Ambient/issues/649 as well

Not all of these are necessary for the launch, but I put all these (somewhat) non-breaking things in an umbrella issue to avoid the fragmentation of 10+ issues floating around and being hard to find. It is something I prefer and helps me focus

**Comment by FredrikNoren** [comment]
Sky is fixed, water is covered in #889
