### ISSUE TITLE
Running from VSCode on Mac always starts with a breakpoint

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#856]
Pressing F5 (or play) in an ambient project always starts with "SIGTRAP". We traced it to possibly having something to do with audio on mac. As a user I would just assume it doesn't work and that it's a crash (would probably not figure out that I can press play again to keep running it).

**Comment by FredrikNoren** [comment]
Disable sentry if debugger is attached

**Comment by Pombal** [comment]
Since https://github.com/AmbientRun/Ambient/commit/d30c2936f935ea043577f9ac0b315556e1267c75, Sentry is only enabled in prod so users running with a debugger shouldn't run into this issue.

**Comment by FredrikNoren** [comment]
@Pombal Hm will that really work? All the nightlies should be built with `production`, and that's what users will be running.

**Comment by Pombal** [comment]
@FredrikNoren Do we have any use case where a user is expected to debug a nightly release built by us? I'd expect users to use a debugger only in development where they build their own code.

**Comment by FredrikNoren** [comment]
@Pombal So from VSCode we're basically just doing: "launch `ambient run` with a debugger", so it's both "debugging" the ambient executable and the users code. This would be the same for release/debug builds and nightly/point releases. Here's the launch configuration for the default ambient template: https://github.com/AmbientRun/Ambient/blob/main/app/src/cli/new_package_template/.vscode/launch.json (`ambient` in this case is the https://github.com/AmbientRun/AmbientCli, which in turn downloads the correct runtime build and runs that)

However, it seems to "work" now (creating a new project and running from vscode doesn't trigger a breakpoint). Not sure why really.

**Comment by Pombal** [comment]
@FredrikNoren Perhaps it "works" because debugging from vscode passes _--features profile_ by default? I would expect the code to be compiled in and run anyway since we're passing the production flag to cargo when building. Is it the case that _--features production_ needs to be passed in when running the executable as well?
