### ISSUE TITLE
[Web] Unity example doesn't render the tree

### ISSUE THREAD

**Issue by ten3roberts** [AmbientRun/Ambient#872]

**Comment by FredrikNoren** [comment]
@ten3roberts The grey floor was expected, but it's also supposed to render a spruce.

**Comment by pierd** [comment]
It loads, it just takes a long time.

<img width="1693" alt="Screenshot 2023-09-20 at 12 14 34" src="https://github.com/AmbientRun/Ambient/assets/752792/c054cbf4-1fc9-4df1-8039-d282171612e0">

**Comment by pierd** [comment]
BTW it takes ~30s to load it in native client for me

**Comment by FredrikNoren** [comment]
I fixed this by fixing the asset download in the nightly build
