### ISSUE TITLE
`ambient` cli did not create config folder (windows), failed to work

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#880]
```
No default runtime version set, installing latest stable version
Runtime version 0.3.0-nightly-2023-09-15 is already installed
Error: The system cannot find the path specified. (os error 3)
```

```
> ambient runtime show-settings-path                  
C:\Users\hi\AppData\Roaming\Ambient\AmbientCli\config\settings.json
```

The folder `config` did not exist inside `AmbientCli` -- so I created the folder and the file (copied from `Ambient\Ambient`) and it overwrote it happily and works fine now. B)

**Comment by FredrikNoren** [comment]
Thanks! Fixed in https://github.com/AmbientRun/AmbientCli/commit/bebe27e30a6fe3ce45a0b7bb3cf86e09bcebf4ff
