### ISSUE TITLE
Set `ambient_runtime` version in examples `ambient.toml`

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#887]
We should update the `ambient_runtime` version, same as we're updating the deployment id, so that when people clone the repo and try to run the examples it tries to use the last functional nightly version of ambient for the example

**Comment by philpax** [comment]
Campfire's version updater can be made to do this pretty easily. What's the behaviour of the CLI with -dev versions? We'd want to keep the examples -dev to avoid updating them every day, and then on release we can cut a tag where they're all 0.3 or such.

**Comment by FredrikNoren** [comment]
@philpax Aren't they being updated every day anyway? Since the deployment id is updated? So figured they could just be updated to latest nightly
