### ISSUE TITLE
Web cursor locking

### ISSUE THREAD

**Issue by ten3roberts** [AmbientRun/Ambient#894]

**Comment by ten3roberts** [comment]
How do we expect cursor locking and stealing to work on the web?

Having the cursor be locked away and hidden may not be the best user experience, especially for the front page.

@philpax you had some clever ideas for this I recall 😊

**Comment by philpax** [comment]
Browsers usually require you to opt into cursor locking by clicking on the element that would lock the cursor, so it might be ok for the front page game. What other concerns are you thinking of?
