### ISSUE TITLE
Clients linger as ghosts

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#902]
After abrupt disconnect clients linger

**Comment by philpax** [comment]
Is this an issue with Tangent specifically? I wasn't using `despawn_recursive` before, so it's possible that something wasn't being cleaned up properly. I've fixed that, let me know if the problem still persists.

**Comment by FredrikNoren** [comment]
Ah ok, let's assume it was and re-open if it was something else

**Comment by pierd** [comment]
Looks like a problem with Tangent indeed. This doesn't happen with Third Person Example.
