### ISSUE TITLE
No auto-completion in the `main` function

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#907]
Repro:

1. `ambient new hello`
2. Open in VSCode
3. No auto-completion is given for anything in the main function

Seems to be something specifically with the `#[main]` macro. `#[element_component]` works (gives auto-completion).

**Comment by philpax** [comment]
I don't know where to get started with fixing this. We could try moving the codegen out of the macro as discussed in the Discord, but apart from that, I have no idea.

**Comment by FredrikNoren** [comment]
@philpax What about just slimming down the macro and making a second macro that generates all the code? Thinking that if it's as slim as possible it _should_ work?

**Comment by philpax** [comment]
Possibly, it's worth a shot. I'll look into it.

**Comment by FredrikNoren** [comment]
It seems like I'm getting auto completion in main in the latest nightly build now

**Comment by Pombal** [comment]
I can confirm that this is working. @philpax feel free to reopen if you still see issues.
