### ISSUE TITLE
Implement Ambient design style in mod manager

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#912]
Using https://github.com/AmbientRun/DesignTokens, we should bring the opaque white Ambient design style to the internal UI. For fonts, we will likely use the official Ambient fonts when it's deployed on the website, and fallback to lookalikes for development / native builds.

**Comment by philpax** [comment]
Note to self: will likely interact with https://github.com/AmbientRun/Ambient/issues/596 while doing this

**Comment by philpax** [comment]
@FredrikNoren this is done, right?

**Comment by FredrikNoren** [comment]
For the mod manager yes
