### ISSUE TITLE
Skinmesh is just a black screen on the web

### ISSUE THREAD

**Issue by pierd** [AmbientRun/Ambient#924]
<img width="1523" alt="Screenshot 2023-09-20 at 12 35 17" src="https://github.com/AmbientRun/Ambient/assets/752792/e752b494-2e97-47b3-b458-ab1e6b256482">

**Comment by ten3roberts** [comment]
What I saw there were initialization errors in the console due to decals.

Decals are currently not supported #834, and something recently changed as the skinmesh didn't use decals previously

**Comment by FredrikNoren** [comment]
@ten3roberts There's nothing about decals in the skinmesh code: https://github.com/AmbientRun/Ambient/blob/main/guest/rust/examples/basics/skinmesh/src/client.rs

**Comment by ten3roberts** [comment]
<img width="1097" alt="image" src="https://github.com/AmbientRun/Ambient/assets/25723553/2b6a1f3e-244f-4b8c-9156-7f0c5f8d8419">
