### ISSUE TITLE
Can't proceed past starting screen for Tangent or AFPS on the web

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#951]
Tangent and AFPS on the web send a reliable network message to the server to set their state (class and name respectively), but this doesn't seem to be processed by the server.

This suggests that
1) the client is not sending a message to the server correctly
2) the server is not handling the message from the client correctly
3) something else is happening

In any case, more investigation is required.

**Comment by philpax** [comment]
Initial testing from @ten3roberts suggests that the WebTransport layer is working correctly (i.e. you can send unistreams from the client to the server). This suggests it's an issue with Ambient specifically.

**Comment by TobiasEnholmX** [comment]
This does not happen everytime for tangent, but it does for AFP. For AFPS i can't get past putting in my name.

**Comment by philpax** [comment]
I can't reproduce this on Tangent with:
- native client on local server
- web client on local server
- web client on remote server
- website + web client

@TobiasEnholmX How often are you seeing this happen?

**Comment by Pombal** [comment]
Tangent seems OK but AFPS still gets an error

![image](https://github.com/AmbientRun/Ambient/assets/526714/d19b0c2e-b1a2-446b-badc-41119b4f97e3)

**Comment by Pombal** [comment]
Now it worked so that's likely
