### ISSUE TITLE
Replace ball rain in Tutorial

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#952]
I realized over the weekend that the ball rain in the tutorial isn't great for networking performance. Maybe we can replace it with something that's a bit better for that.

**Comment by philpax** [comment]
If you end up doing this, can you create a repo with the state of the tutorial at the end of each chapter ( https://github.com/AmbientRun/Ambient/issues/956#issuecomment-1737217895 ) ?

Otherwise, let me know when you're done and I'll create that repo afterwards.

**Comment by FredrikNoren** [comment]
@philpax Go ahead
