### ISSUE TITLE
Tutorial QOL improvements

### ISSUE THREAD

**Issue by Pombal** [AmbientRun/Ambient#956]
- [x]  In code snippets, the copy to clipboard button adds `fn main` but that's not desirable.
- [x] The run button doesn't work so we could consider removing it.
- [ ] Consider including the use statements that are needed for each snippet to work.
- [x] Add more context on where the code snippets should be added, it's not clear.
- [x] Green cubes on chapter 3 seem to appear in the wrong place.
- [x] Cube colliders on chapter 2 seem to be the wrong size.

**Comment by FredrikNoren** [comment]
Green cubes thing is fixed

**Comment by FredrikNoren** [comment]
Cube colliders are fixed

**Comment by philpax** [comment]
I've fixed the presence of the play button, which also seems to have fixed the `fn main` wrapping in https://github.com/AmbientRun/Ambient/commit/eee5080a31002cbb2f59dc7e775a8c2fe90e9daa .

I think we want to encourage people to get used to importing anything that isn't specified. That's the only thing stopping this issue from being closed out - should we update the tutorial with use statements or leave it as-is?

**Comment by Pombal** [comment]
A few users had issues finding the correct use statements, especially for asset importing. Rust Analyzer didn't help. Perhaps we can add reminders of the use statements just before the code snippet instead of adding them directly?

**Comment by philpax** [comment]
> A few users had issues finding the correct use statements, especially for asset importing.

Aha - I think I've fixed all of the references to `assets` in the tutorial to be properly package-scoped, so they should hopefully just work. There are a few in the rest of the non-tutorial docs, but I'll get to them later.

> Rust Analyzer didn't help. 

I'm looking into this with #907, but I'll admit I'm not particularly hopeful at this stage.

> Perhaps we can add reminders of the use statements just before the code snippet instead of adding them directly?

Hmm, how so? We have a few reminders the first time that you'll need to import things, but that probably won't help if R-A isn't working. What kind of reminders are you thinking of?

**Comment by Pombal** [comment]
> I think I've fixed all of the references to assets in the tutorial to be properly package-scoped

Great, perhaps this is enough to close this issue then.

> What kind of reminders are you thinking of?

I was thinking that just before displaying a code snippet we could expliicitly say what imports are necessary to make it work. But this seems overkill. Making sure that uses are package scoped seems like a better solution.

>  it might be a good idea to publish a canonical version of the tutorial's code at the end of each chapter

Yep, sounds useful!

**Comment by philpax** [comment]
> Yep, sounds useful!

Cool, I'll leave this issue open until I do that, then.

**Comment by philpax** [comment]
Done in abfcf531df4bfa167a6414ed462665503584ed7b
