### ISSUE TITLE
Ambient CLI takes too long too install

### ISSUE THREAD

**Issue by Pombal** [AmbientRun/Ambient#958]
Investigate removing dependencies to reduce install times

**Comment by FredrikNoren** [comment]
I looked into getting rid of ssl (which I suspect is the big one). Downloading from google storage seems possible over http, but listing isn't (i.e. this will only run over https: `"https://storage.googleapis.com/storage/v1/b/ambient-artifacts/o?prefix=ambient-build&alt=json"`). Guess we could set up a proxy, but not sure it's worth having to manage that.

**Comment by simne** [comment]
> I looked into getting rid of ssl (which I suspect is the big one).

SSL is not good choice, because it is now standard de facto, and because it have different versions in Ubuntu current and in LTS.

Fortunately, on LTS successfully compiled Ambient from sources with LTS packages, but this is time consuming, and in future SSL API compatibility could broke and it could severe limit new participants.

**Comment by Pombal** [comment]
https://github.com/AmbientRun/AmbientCli/commit/3561166a1de719432c15b785bf3232c66efc55ea and https://github.com/AmbientRun/AmbientCli/commit/d2909a872f5539e8754f4e663da838c10db0d56d reduce install times substantially. Can we close this?

**Comment by philpax** [comment]
Ah ok - happy to close this if it's <1 minute on an "average" game dev PC. Do we have a way of testing it?

**Comment by droqen** [comment]
@philpax Send me the command(s?) I need to run to test this, will run it & report back

I have Ambient installed, if I need to uninstall it first or something lmk that too

**Comment by philpax** [comment]
Okay, yep!

`cargo install ambient` takes 15.47s on my M1 Max laptop, which is more than acceptable for me.

@droqen can you try that now and mention what CPU you have?

**Comment by droqen** [comment]
`Finished release [optimized] target(s) in 32.90s`
`Processor - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz`

**Comment by philpax** [comment]
> `Finished release [optimized] target(s) in 32.90s` `Processor - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz`

tyvm 🚀
