### ISSUE TITLE
All black model, material import failed - Example

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#960]
[hermaneubis_yellow_and_nomat.zip](https://github.com/AmbientRun/Ambient/files/12717473/hermaneubis_yellow_and_nomat.zip)

Contains two .blend and .glb files: "nomat" and "yellow"

"nomat" imports into Ambient just fine:

![image](https://github.com/AmbientRun/Ambient/assets/5104632/0d212ab1-2d48-4347-b472-d0e19eab4e26)

"yellow" imports into Ambient as a black shape which ignores lighting and fog:

![image](https://github.com/AmbientRun/Ambient/assets/5104632/95bc0cd1-a389-425a-bbf0-6d44bcc2650c)

The only difference is that in "yellow" I have assigned a single material to the model in Blender. I have exported both to .glb using default settings except I have checked `Include > Limit to [x] Selected Objects`

Screenshots taken from the latest `alex/lightbox_playground` in the `alex-scene-branch` of Ambient

**Comment by marceline-cramer** [comment]
Maybe related to #115 and #720?

**Comment by philpax** [comment]
@ten3roberts Just confirming, does #961 fix this?
