### ISSUE TITLE
Implement package versioning

### ISSUE THREAD

**Issue by philpax** [AmbientRun/Ambient#989]
At present, packages are fetched via deployment ID, which 'works' but means there's no easy way to tell one version apart from each other. It also means the packages in your system must line up *exactly*, which gets harder with each package you add.

Instead, we should implement proper semver. Packages should be referred to by version, and a (basic) solver should be present that should try to unify the state of the system so that all packages can run, even if their exact dependencies are slightly misaligned.

This is a very deep rabbit hole, so I imagine we will get a basic implementation in and improve it over time.

**Comment by ten3roberts** [comment]
Would go hand in hand with my comment on #1002

**Comment by philpax** [comment]
Basic implementation:
- Extend API to allow fetching packages by version
- Remove the use of specific deployments
