### ISSUE TITLE
`camera::world_to_screen` should handle behind camera positions better

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#991]
Currently `camera::world_to_screen` displays positions behind the camera on the screen.

![behind](https://github.com/AmbientRun/Ambient/assets/5104632/e6771034-24cb-4925-b94e-25e923272359)

EDIT:: It should output Vec3, including the post-projection z-position (see discussion below)

**Comment by droqen** [comment]
@philpax 's comments from discord
> we should probably just return more information
> normally with a w2s you're told if it's off-screen so you can decide what you want to do with that (usually clip at the borders so that you can have icons and such)

**Comment by droqen** [comment]
but the main issue for foggy scene is this 'behind the camera' behaviour.

**Comment by FredrikNoren** [comment]
@droqen So I think the function works as expected, but when you use it you'll need to check the outputted z-value. We could also add a comment about that in the docs of it.

**Comment by philpax** [comment]
It doesn’t return a z-value right now; it gets truncated to 2D. I’m thinking we return a tuple of (Vec2, bool) where the bool represents if it’s in screen or not.

**Comment by philpax** [comment]
Do you have any examples? I’ve only ever really needed the in/out of screen state. We can expose the full thing, just wondering if it’s something users will actually need.

**Comment by FredrikNoren** [comment]
Yeah for instance if I want to draw some HUD in connection to some things in the world, I might want to z-sort that, but it's still in the UI layer.

**Comment by philpax** [comment]
Yeah fair enough, good point.

**Comment by droqen** [comment]
+1 to directly passing the z-value! Different users might want to clip z differently, and I would have used z-value for nameplate scaling in cold chicken
